### ISSUE TITLE
solr w/ xConnect

### ISSUE THREAD

**Issue by jeanfrancoislarente** [Sitecore/docker-images#10]
I've added my initial attempt at solr with xConnect by trying to follow @pbering original approach but copying some of the things from @Jonne & @joostmeijles 

If someone could take this and make it work now that would be great. Hopefully I've got a lot of the stuff meshed together where it's just some minor cleanup & tweaking.

feature/solr-xp branch

**Comment by joostmeijles** [comment]
@jeanfrancoislarente what is the issue with it? 
I hope that have some time this week to have a look.

**Comment by rsenk** [comment]
I think that you can use [Sitecore Install Extensions](https://github.com/SoftServeInc/SitecoreInstallExtensions) (SIX). This is Powershell module available on GitHub and Powershell Gallery. This module is an extension to the SIF and works in the same way like SIF. This module provides two ways to install and configure SOLR as a service. Additionally, there are tasks to setup HTTPS and generate certificates.  One way is using NSSM and the second one do not depend on any external module. If you decide to use it I can prepare proper JSON files for you.

**Comment by jeanfrancoislarente** [comment]
Issue so far is just finalizing the Dockerfile. It gets to the Install-SitecoreConfiguration steps. There's a variable value not replacing correctly and it fails.

I'm simply unable to push it forward due to a looming deadline. I will be able to resume on contributions 1st or 2nd week of April and will be happy to!

**Comment by pbering** [comment]
@jeanfrancoislarente, @rsenk, I think you have may have misunderstood Docker a bit, you don't *install* services or start multiple processes in a container... 1 container == 1 process (ENTRYPOINT/CMD). So in this case it is the solr.cmd (which starts a java.exe process). If the process stops / dies, the container dies as well.

**Comment by jeanfrancoislarente** [comment]
I never pretended to understand it. I'll definitely learn it - but I'm admitedly extremely fresh in the Docker world.

**Comment by rsenk** [comment]
@pbering Yes, true, but in SIX is code to reuse it.
