### ISSUE TITLE
ERROR: manifest for sitecore-xm-solr:9.2.0-nanoserver-1809 not found

### ISSUE THREAD

**Issue by sshushliapin** [Sitecore/docker-images#103]
Building an image based on Sitecore 9.2 containers:

```
Pulling solr (mycomp.azurecr.io/sitecore-xm-solr:9.2.0-nanoserver-1809)...
ERROR: manifest for mycomp.azurecr.io/sitecore-xm-solr:9.2.0-nanoserver-1809 not found: manifest unknown: manifest unknown
```

That happens because tests use [nanoserver version 1803](https://github.com/Sitecore/docker-images/blob/master/windows/tests/9.x.x/.env#L3) which is not created OOTB. For 9.2 the expected version is `1903`.

**UPDATED:** [nanoserver version 1809](https://github.com/Sitecore/docker-images/blob/master/windows/tests/9.x.x/.env#L3), not 1803.

**Comment by pbering** [comment]
Hi there, something else is wrong, the .env files has the correct nanoserver version right now, which is 1809, the version that matches ltsc2019 which is also 1809.

How does your Invoke-Build command look like?

**Comment by sshushliapin** [comment]
I use [this script](https://github.com/Sitecore/docker-images#configure-your-build-server) with no changes. Tags for 9.2: `"*:9.2.0*1903"` and `"*:9.2.0*ltsc2019"`. That's what I've got in `sitecore-xm-solr` repo:

![image](https://user-images.githubusercontent.com/4719165/67605852-4367cd80-f788-11e9-9393-415bf2ecb0d6.png)

Should there be tag `9.2.0-nanoserver-1803`?

**Comment by pbering** [comment]
That could be one of the old ones (in the .\legacy folder). 1803 is not built anymore by default.

**Comment by sshushliapin** [comment]
Ah, sorry, I wrote `1803` in the description which is indeed obsolete. The version in the error is `1809` but in my repo I can see `1903` only (see screenshot).

**Comment by sshushliapin** [comment]
> the version that matches ltsc2019 which is also 1809.

It seems there is an issue in the dependency detection. That's what I see for `"*:9.2.0*ltsc2019"` tag:

![image](https://user-images.githubusercontent.com/4719165/67616845-092d1900-f7e6-11e9-83e5-f96fa734f591.png)

I changed the tag to cover all the 9.2 versions (`"*:9.2.0*"`). Now I've got my missing `9.2.0-nanoserver-1809` image but isn't it a bug?

**Comment by pbering** [comment]
Yeah something is off, `"*:9.2.0*ltsc2019"` should also auto include nanoserver 1809, I will look into that, thanks!

**Comment by pbering** [comment]
I was mistaken, it not a bug, it's how it's supposed to be working currently. 

If you **don't** specify a `-Tags` value then the **default value** will be the current version which is: `"*:9.2.0*ltsc2019", "*:9.2.0*1809"` (see https://github.com/Sitecore/docker-images/blob/master/modules/SitecoreImageBuilder/SitecoreImageBuilder.psm1#L722)

`ImplicitTagsBehavior` works "within a os" because there are no "ltsc2019" images that uses a "nanoserver" image as a *base* image (would be very strange). You can use the `-Verbose` switch so see why and when it includes another image.

Makes sense?

**Comment by sshushliapin** [comment]
If I do not specify tags, yes, it works. If I do set `"*:9.2.0*ltsc2019"` it [does not resolve nano 1809](https://github.com/Sitecore/docker-images/issues/103#issuecomment-546583738).

Is it illegal to use `"*:9.2.0*ltsc2019"` tag?

**Comment by pbering** [comment]
No not illegal but you will ONLY get ltsc2019...

`-Tags "*:9.2.0*ltsc2019"` will only give you ltsc2019 images, but `-Tags "*:9.2.0*ltsc2019", "*:9.2.0*1809"` will give you both.

For 1903 it's easier with ONLY `-Tags "*:9.2.0*1903"` since there is no ltsc2019 version.

**Comment by sshushliapin** [comment]
> -Tags "*:9.2.0*ltsc2019" will only give you ltsc2019 images, but -Tags "*:9.2.0*ltsc2019", "*:9.2.0*1809" will give you both

sorry, I do not see the diff :)

**Comment by pbering** [comment]
Sorry I can't explain in more clearly for you :)

Consider these trees of images:

```
sitecore-xm-sxa-cm:9.2.0-windowsservercore-ltsc2019
    - sitecore-xm-spe-cm:9.2.0-windowsservercore-ltsc2019
        - sitecore-xm-cm:9.2.0-windowsservercore-ltsc2019
            - mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019
                - mcr.microsoft.com/windows/servercore/iis:ltsc2019
                    - mcr.microsoft.com/windows/servercore:ltsc2019

sitecore-xm-sxa-solr:9.2.0-nanoserver-1809
    - sitecore-openjdk:8-nanoserver-1809
        - mcr.microsoft.com/windows/nanoserver:1809
```

Using `-Tags "*:9.2.0*ltsc2019"` will only select the *first* tree (it's a simple `-like` on the tag name) and `-ImplicitTagsBehavior "Include"` makes sure that the build order will be correct from bottom up.

There are absolute nothing that "connects" or makes any dependencies between `sitecore-xm-sxa-cm` and `sitecore-xm-sxa-solr`, the only connection there is is a "soft" one in the definition of the `xm` topology that requires the `solr` and `cm` to be present.

Better? :)

**Comment by sshushliapin** [comment]
You mentioned the same tag twice in different scenarios. That was confusing :)

![image](https://user-images.githubusercontent.com/4719165/67620236-638da000-f80d-11e9-8315-26fe6d2bccf3.png)

I guess it's ok, I'll just use `"*:9.2.0*"` and everything will work.

**Comment by pbering** [comment]
On purpose... `-Tags` is an array of strings.

**Comment by sshushliapin** [comment]
Now I got it... Makes sense, thanks!
