### ISSUE TITLE
[Build] Cleanup <none> intermediate containers after build is complete

### ISSUE THREAD

**Issue by stephenpope** [Sitecore/docker-images#109]
After running `Build.ps1` for the first time, lots of intermediate containers (\<none\>) are left behind ..

![image](https://user-images.githubusercontent.com/689099/67863239-6e04ae00-fb1b-11e9-9031-88db1bd333d1.png)

.. running a `docker image prune -f` when the build is complete would help tidy things up a bit! (12.32Gb on my local machine) or at least add the option to do this as a flag.

![image](https://user-images.githubusercontent.com/689099/67863327-9b515c00-fb1b-11e9-9126-9f343447a70b.png)

**Comment by pbering** [comment]
We should **not** do this as part of "Invoke-Build", too many side effects if you run on build agents that runs other jobs that uses the same Docker engine, docker image prune is too "wide" and will take everything.

Users should handle this by them selves as "normal" administration of build agents or add it lastly in their own build jobs.

**Comment by stephenpope** [comment]
Should we add instruction to help them clean this stuff up (for those missing this knowledge) ?

**Comment by pbering** [comment]
Yeah, it could be a nr 3 under https://github.com/Sitecore/docker-images#configure-your-build-server. Trigger a prune once a week (that's how we do it).
