### ISSUE TITLE
How do I run composed images and access Sitecore instance in a container?

### ISSUE THREAD

**Issue by sergeyshushlyapin** [Sitecore/docker-images#11]
Would be great to add a wiki page describing that.

I suppose each container needs to be started individually now. Would it be possible to use `docker-compose` as in the original @pbering's [solution](https://github.com/pbering/sitecore-nine-docker#usage)?

**Comment by pbering** [comment]
Hi, for now you can use this: https://invokecommand.net/posts/circle-is-complete-solr-image-added, but in near future we will have all examples, guide, etc on https://github.com/Sitecore/docker-demo

**Comment by sergeyshushlyapin** [comment]
Good, thanks!
