### ISSUE TITLE
Add SXA+JSS Containers for XM and XP.

### ISSUE THREAD

**Issue by peternazarov** [Sitecore/docker-images#125]

**Comment by bplasmeijer** [comment]
folders:
/windows/9.x.x/sitecore-jss
/windows/9.x.x/sitecore-jss-ps
/windows/9.x.x/sitecore-sxa-jss
/windows/9.x.x/sitecore-sxa-jss-ps

**Comment by peternazarov** [comment]
The provisional lists of New Images and Docker Compose files for 9.3.0:

Images:
 - xm-jss-cm
 - xm-jss-cd
 - xm-jss-sqldev 
 - xm-jss-ps-cm
 - xm-jss-ps-cd
 - xm-jss-ps-sqldev
 - xm-sxa-jss-cm
 - xm-sxa-jss-cd
 - xm-sxa-jss-sqldev
 - xm-sxa-jss-ps-dm
 - xm-sxa-jss-ps-sqldev
 - xp-jss-standalaone
 - xp-jss-cd
 - xp-jss-sqldev
 - xp-jss-ps-standalaone
 - xp-jss-ps-cd
 - xp-jss-ps-sqldev
 - xp-sxa-jss-standalaone
 - xp-sxa-jss-cd
 - xp-sxa-jss-sqldev
 - xp-sxa-jss-ps-standalaone
 - xp-sxa-jss-ps-cd
 - xp-sxa-jss-ps-sqldev

Docker Compose YML files:
 - xm-jss
 - xm-jss-ps
 - xm-sxa-jss
 - xm-sxa-jss-ps
 - xp-jss
 - xp-jss-ps
 - xp-sxa-jss
 - xp-sxa-jss-ps

**Comment by GoranHalvarsson** [comment]
How is the status of this one?

**Comment by peternazarov** [comment]
Testing the 9.3 images atm. Waiting for @bplasmeijer to merge 9.2 related PR which is a pre-requisite for this one: https://github.com/Sitecore/docker-images/pull/128
