### ISSUE TITLE
Prepare an image for development

### ISSUE THREAD

**Issue by AlbertoLeon** [Sitecore/docker-images#143]
Hi all,
I would like to prepare a development image that contains together all the requirements to run Sitecore XP Single.

Before reinvent the wheel I would like to listen to your advices.
How much difficult could be putting the minimum of services in the same image?

**Comment by pbering** [comment]
Hi, it's **not** recommend to run XP single in a single container, it's simply too resource intensive for Docker and Windows to handle it and the performance is terrible. Also it's considered best practice to only run 1 process per container.

**Comment by pbering** [comment]
Out of curiosity, why would you run everything in 1 container?

**Comment by AlbertoLeon** [comment]
> Out of curiosity, why would you run everything in 1 container?

I want one image for each development and I could have like 5 sitecore developments at the same time.
As the proposal here are 9 images:
sitecore-xp-solr                        9.2.0-nanoserver-1809              16a0bd9969db        21 hours ago        654MB
sitecore-xp-xconnect-processingengine   9.2.0-windowsservercore-ltsc2019   36d1d5601221        23 hours ago        7.7GB
sitecore-xp-xconnect-automationengine   9.2.0-windowsservercore-ltsc2019   59457dfb353a        23 hours ago        7.7GB
sitecore-xp-xconnect-indexworker        9.2.0-windowsservercore-ltsc2019   ec4fa5fd0da6        40 hours ago        7.72GB
sitecore-xp-identity                    9.2.0-windowsservercore-ltsc2019   6ab0d469ca12        40 hours ago        8.81GB
sitecore-xp-cd                          9.2.0-windowsservercore-ltsc2019   7a2bb12a50c1        40 hours ago        9.19GB
sitecore-xp-standalone                  9.2.0-windowsservercore-ltsc2019   d2b868b25ba7        41 hours ago        9.19GB
sitecore-xp-sqldev                      9.2.0-windowsservercore-ltsc2019   b28e43341a45        41 hours ago        7.15GB
sitecore-xp-xconnect                    9.2.0-windowsservercore-ltsc2019   4c5fcd73a45e        41 hours ago        8.17GB

These are aprox 65GB. I can't imagine all that disc size  multiplied for each development. I would like to dedicate 10GB or 15GB for each development. I though that putting all in one image could help on that.

**Comment by pbering** [comment]
the size in NOT multiplied. Each layer in each image is shared, for example `mcr.microsoft.com/dotnet/framework/aspnet` is 6 GB, but is based on `mcr.microsoft.com/windows/servercore` which is 5 GB, so in reality the ASPNET image is only 1 GB. The same applies for our Sitecore images.

**Comment by AlbertoLeon** [comment]
You can close it, thanks for the help
