### ISSUE TITLE
Set-LicenseEnvironmentVariable.ps1 doesn't work properly

### ISSUE THREAD

**Issue by Antonytm** [Sitecore/docker-images#149]
Steps to reproduce:

1. Run `Set-LicenseEnvironmentVariable.ps1 -Path C:\license\license.xml`

Expected result: $env:SITECORE_LICENSE contains GZip>Base64 license.xml file
Actual result: $env:SITECORE_LICENSE always contains H4sIAAAAAAAEAA==

P.S. Doesn't matter file content, it as output I always get "H4sIAAAAAAAEAA=="

**Comment by pbering** [comment]
Sounds like an issue that was fast fixed two days ago: https://github.com/Sitecore/docker-images/issues/146, can you verify you have pulled after this fix?

**Comment by Antonytm** [comment]
Thank you @pbering 

Setting license enthronement variable using Powershell Core v6 + works.

However, with Powershell 5, it still doesn't work for me.
PS 6 and PS 5 generates different results on same script(I guess it could be normal, because probably GZip implementation is different). Sitecore throws exception: Invalid length for a Base-64 char array or string.

![image](https://user-images.githubusercontent.com/647813/69918686-ded21980-147d-11ea-8c41-5476277eb178.png)

**Comment by pbering** [comment]
hmm can you paste the output of `$PSVersionTable` of your PS 5? Mine is working and looks like this:

```
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by Antonytm** [comment]
Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      5.1.18362.145                                                                                                                             
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.18362.145                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1

**Comment by Antonytm** [comment]
Exact the same. 
Should running of Set-LicenseEnvironmentVariable.ps1 -Path C:\license\license.xml on PS 5.1 and on PS Core 6+ return the same value?

**Comment by pbering** [comment]
yeah... how about:

```
PS D:\> [System.IO.Compression.GZipStream].AssemblyQualifiedName
System.IO.Compression.GZipStream, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
PS D:\> [System.Convert].AssemblyQualifiedName
System.Convert, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
```
Guess you have the same...

But now, PS5 and PS6 doesn't give the same value but here both works. I looks like the gzipping is a bit different on .NET Full framwork (PS 5) and .NET Core (PS 6).

**Comment by Antonytm** [comment]
The same
```
[System.IO.Compression.GZipStream].AssemblyQualifiedName
System.IO.Compression.GZipStream, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System.Convert, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
```

**Comment by pbering** [comment]
I don't get it, completely the same ... can you verify that your Set-LicenseEnviromentVariable.ps1 is exactly the same as https://github.com/Sitecore/docker-images/blob/efbfee85d0aa9066b0fc5ba561d0c18c927e1d5c/Set-LicenseEnvironmentVariable.ps1? I'm not sure how else to make something that works consistently between PowerShell versions, do you have any suggestions?

**Comment by jajvisser** [comment]
I also had this issue. My issue was that i originally ran the `Set-LicenseEnvironmentVariable.ps1` from cmd as `powershell .\Set-LicenseEnvironmentVariable.ps1 -Path C:\license\license.xml -PersistForCurrentUser`

This gave a different base64 result of the license file in my environment variables compared to running it directly from powershell even though the `$PSVersionTable` gives the same result.

**Comment by pbering** [comment]
A new version of  `Set-LicenseEnvironmentVariable.ps1` has just been merged (see https://github.com/Sitecore/docker-images/pull/191), would you guys please test and see if it works better for you?

IF not then can you try to use this alternate approach: 

```PowerShell
$env:SITECORE_LICENSE = (docker run --rm -v C:\license\license.xml:/license.xml ubuntu:19.10 /bin/sh -c 'cat /license.xml | gzip -f | base64')
```

**Comment by pbering** [comment]
@jajvisser, @Antonytm did you have a chance to test the latest version?

**Comment by phaniav** [comment]
@pbering , I pulled the latest master today and I am still running into this issue. I am using PS5

```
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
Ran into the license issue

![image](https://user-images.githubusercontent.com/3968213/72214804-1a292480-34cf-11ea-8acb-7db63367eeb1.png)

Apart from the above, this issue is present in xconnect processing engine logs also.

```
xconnect-processingengine_1  | 00:02:48:636: Sitecore Development ENTRYPOINT, starting...
xconnect-processingengine_1  | 00:02:48:714: Skipping start of 'Watch-Directory.ps1', to enable you should mount a directory into 'C:\src'.
xconnect-processingengine_1  |
xconnect-processingengine_1  | Starting Processing Engine...
xconnect-processingengine_1  | ERROR
xconnect-processingengine_1  |
xconnect-processingengine_1  |
xconnect-processingengine_1  | System.FormatException: Invalid length for a Base-64 char array or string.
xconnect-processingengine_1  |    at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
xconnect-processingengine_1  |    at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
xconnect-processingengine_1  |    at System.Convert.FromBase64String(String s)
xconnect-processingengine_1  |    at Sitecore.XConnect.Configuration.Extensions.ConvertBase64LicenseFile(String encodedLicense)
xconnect-processingengine_1  |    at Sitecore.XConnect.Configuration.Extensions.AddXConnectRuntimeDefaults(IConfigurationBuilder builder, String machineName, String instanceName, String licensePath, String roleName, String sitecoreVersion, IEnvironmentConfiguration environmentConfiguration, String environmentName)
xconnect-processingengine_1  |    at Sitecore.XConnect.Configuration.Extensions.AddXConnectDefaults(IConfigurationBuilder builder, String machineName, String instanceName, String configDirectory, String configEnvironmentSetting, String[] additionalConfigParameters, String roleName, String sitecoreVersion)
xconnect-processingengine_1  |    at Sitecore.XConnect.Configuration.Extensions.AddXConnectDefaults(IConfigurationBuilder builder, String machineName, String instanceName, String configDirectory, String configEnvironmentSetting, String[] additionalConfigParameters)
xconnect-processingengine_1  |    at Sitecore.Processing.Engine.Hosting.HostBuilder.CreateServiceCollection(IHostBuilderOptions options, IConfigurationBuilder configurationBuilder, String configurationEnvironmentName)
xconnect-processingengine_1  |    at Sitecore.Processing.Engine.Hosting.HostBuilder.Build(IHostBuilderOptions options, IConfigurationBuilder configurationBuilder)
xconnect-processingengine_1  |    at Sitecore.Processing.Engine.App.Program.RunAsConsoleApp()
93x_xconnect-processingengine_1 exited with code 0
```

**Comment by pbering** [comment]
Hmm a bit surprised that you did not see an exception when running the script! This line should blow up: https://github.com/Sitecore/docker-images/blob/master/Set-LicenseEnvironmentVariable.ps1#L46 in case the length of the license value is shorter than excepted (to catch errors before trying to start compose).

**Comment by phaniav** [comment]
I found the problem with the license this morning while spinning a new docker-compose.
`docker-compose -f .\docker-compose.xp.sxa.ps.yml up`

For 9.2, I have configured the .env file which docker-compose will use for setting the environment. I used the same procedure for 9.3 also which caused the issue in the first place.

`SITECORE_LICENSE=c:\license` configuring this overrode the license string set in `Set-LicenseEnvironmentVariable.ps1`. Once I removed the `c:\license` from `.env` file, I was able to successfully login.


```
REGISTRY=
WINDOWSSERVERCORE_VERSION=1903
NANOSERVER_VERSION=1903
SITECORE_VERSION=9.3.0
SITECORE_LICENSE=c:\license
```

**Comment by pbering** [comment]
@phaniav glad you found the issue :) 

@Antonytm is your issue similar or did you try latest version?

**Comment by jrudley** [comment]
I have the same issue with 9.3.0. Pulled from today's master branch

**Comment by pbering** [comment]
in pre 9.3.0 version the environment variable `SITECORE_LICENSE` was the path to a folder where the license.xml is inside the container and was only used in compose when setting up the volumes. The pre 9.3.0 images was hardcoded to look for the license in C:\license. 9.3.0. Newer images is not hardcoded anymore and are using `SITECORE_LICENSE` directly and are expecting the value not to be a path but the actual value of the license file gzipped and base64 encoded. If you prefer not to do this and want it mount in the license you can set the path where Sitecore should look for it in `SITECORE_LICENSE_LOCATION` which behaves much like pre 9.3.0.

**Comment by jrudley** [comment]
Thanks for explaining the version behavior differences. This makes much
more sense to me now. Cheers

**Comment by pbering** [comment]
I will close this for now as it seems that most has resolved their problems. Will keep it as pinned for future reference.

**Comment by hermanussen** [comment]
I had this same issue. But after making the changes in the PR here, it seems to work.
https://github.com/Sitecore/docker-images/pull/240#issue-373068683

Not sure why this is though.

**Comment by dcouto** [comment]
> I also had this issue. My issue was that i originally ran the `Set-LicenseEnvironmentVariable.ps1` from cmd as `powershell .\Set-LicenseEnvironmentVariable.ps1 -Path C:\license\license.xml -PersistForCurrentUser`
> 
> This gave a different base64 result of the license file in my environment variables compared to running it directly from powershell even though the `$PSVersionTable` gives the same result.

I'm pretty confident this was my issue too.
