### ISSUE TITLE
Compose file docker-compose.xp.yml doesn't work

### ISSUE THREAD

**Issue by Antonytm** [Sitecore/docker-images#150]
Steps to reproduce:

1. cd .\windows\tests\9.3.x\
2. docker-compose --file .\docker-compose.xp.yml up
3. docker ps
4. Find container id of 93x_cm_1. Get [CONTAINER_ID] from the output table.
5. docker exec [CONTAINER_ID] ipconfig. Get [IP_ADDRESS] from the output table.
6. Open http://[IP_ADDRESS]/sitecore in browser

Expected result:
Sitecore login screen is appeared.
Actual result:
_The network path was not found_ exception in browser.
![image](https://user-images.githubusercontent.com/647813/69919905-9cfba000-148a-11ea-9b7f-9700f731be29.png)

Multiple exceptions in logs.
![image](https://user-images.githubusercontent.com/647813/69919900-953bfb80-148a-11ea-9ad0-bd1d5c9d5365.png)
![image](https://user-images.githubusercontent.com/647813/69919951-201cf600-148b-11ea-9cef-47f47a0ecbc9.png)

I think that something wrong is with SQL configuration. 
**sql_93x_1 exited with code 1**
Which causes absence of this container in list of running containers
![image](https://user-images.githubusercontent.com/647813/69919991-8a359b00-148b-11ea-9eb7-3b6c158cf241.png)

**Comment by Antonytm** [comment]
Update: Latest logs from SQL container:

Attaching to 93x_sql_1, 93x_solr_1, 93x_xconnect_1, 93x_xconnect-indexworker_1, 93x_xconnect-automationengine_1, 93x_xconnect-processingengine_1, 93x_cm_1, 93x_cd_1
sql_1                        | ### Existing Sitecore databases found in 'C:\\data\\'...
sql_1                        | ### Attaching 'Sitecore.Core'...
sql_1                        | ### Attaching 'Sitecore.Experienceforms'...
sql_1                        | ### Attaching 'Sitecore.Master'...
sql_1                        | ### Attaching 'Sitecore.Sessions'...
sql_1                        | ### Attaching 'Sitecore.Web'...
sql_1                        | ### Preparing Sitecore databases...
sql_1                        | Invoke-Sqlcmd : Invalid object name
sql_1                        | 'Sitecore.Xdb.Collection.ShardMapManager.__ShardManagement.ShardsGlobal'.
sql_1                        | At C:\Boot.ps1:44 char:1
sql_1                        | + Invoke-Sqlcmd -Query ("UPDATE [Sitecore.Xdb.Collection.ShardMapManage ...
sql_1                        | + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sql_1                        |     + CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlPowerS
sql_1                        |    hellSqlExecutionException
sql_1                        |     + FullyQualifiedErrorId : SqlError,Microsoft.SqlServer.Management.PowerShe
sql_1                        |    ll.GetScriptCommand
sql_1                        |

**Comment by Antonytm** [comment]
After this fix docker-compose.xp.yml configuration is still not stable, but at least you can start it

**Comment by pbering** [comment]
I see ` sql_1 | ### Existing Sitecore databases found in 'C:\data\'...` which mean that the sql boot script will not seed fresh databases. Can you try to do `docker-compose down` and the run .\Clean-Data.ps1 and then start up again?

**Comment by Antonytm** [comment]
.\Clean-Data.ps1 helped me.

These steps before running docker-compose.xp.yml cause this issue
1. cd .\windows\tests\9.3.x\
2. docker-compose --file .\docker-compose.xm.yml up
3. do something
4. docker-compose --file .\docker-compose.xp.yml up

Looks like same file paths in 9.3.x\data for docker-compose.xp.yml and docker-compose.xm.yml cause this issue.

I don't think that files paths needs to be changed to be different for both configuration. Because in day to day work configurations will be copied to some locations and be started from there. I close issue.

You can reopen it, if running docker-compose.xp.yml and docker-compose.xm.yml from same folder is required.

**Comment by pbering** [comment]
Glad it worked!
