### ISSUE TITLE
ltsc2019: Pulling from windows/servercore: no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by svdoever** [Sitecore/docker-images#159]
Get the error:

```
### Build specifications loaded...                                                               
ltsc2019: Pulling from windows/servercore                                                        
no matching manifest for linux/amd64 in the manifest list entries                                
Failed.                                                                                          
At C:\P\sitecore-docker-images\modules\SitecoreImageBuilder\SitecoreImageBuilder.psm1:203 char:78
+ ... CODE -ne 0 | Where-Object { $_ } | ForEach-Object { throw "Failed." }                      
+                                                         ~~~~~~~~~~~~~~~                        
    + CategoryInfo          : OperationStopped: (Failed.:String) [], RuntimeException            
    + FullyQualifiedErrorId : Failed.                                                            
                                                                                                 
```

Any idea what to do about it?

**Comment by svdoever** [comment]
call me stupid... had to switch Docker to Windows containers...

**Comment by jamiecook** [comment]
Not stupid, I just had the exact same problem and also had no idea that "switching to windows containers" was even a thing.

**Comment by Theeiss** [comment]
Definitely not stupid! Same problem here and I had no idea how to deal with it hahaha. Thanks for posting!

**Comment by DesKevinMendez** [comment]
Going to icon of docker, and click on: "Switch to windows containers..."

**Comment by LoneWanderer-GH** [comment]
> 
> 
> call me stupid... had to switch Docker to Windows containers...

On windows, right clic on the taskbar tray icon:
![image](https://user-images.githubusercontent.com/19716859/117329487-f85a6a80-ae94-11eb-80bd-67246bbb25c7.png)

Popup :
![image](https://user-images.githubusercontent.com/19716859/117329562-0c9e6780-ae95-11eb-8ad6-c91054060b6d.png)

To switch back:
![image](https://user-images.githubusercontent.com/19716859/117329671-2cce2680-ae95-11eb-9266-f75fe3c5b97e.png)

**Comment by hoffstadt1004** [comment]
Still not Stupid same here, thanks for sharing.

**Comment by crazyfrog768** [comment]
I don't have Switch to Windows container  ' choice ' ?
docker desktop 4.11.1

**Comment by MatheusMaroli** [comment]
hi guys, after i change windows container my docker stay starting but never started, do you have any idea ?

**Comment by EosWaxDev** [comment]
Windows containers just won't start.

**Comment by MatheusMaroli** [comment]
I remember when installed docker on windows home, i take make some configurations on windows hyperview. But i don't know if is relationships

**Comment by BadrulAlomIOG** [comment]
Just to be clear it was the task bar icon for Dokcer (bottom right) and not application running icon of docker (bottom) that needs the right click..

**Comment by AsquzeRR** [comment]
I solved this problem by changing the docker Linux to windows by right click on the docker icon in the services bar, then clicking on Switch to windows containers.

**Comment by ashishsutariya** [comment]
> Just to be clear it was the task bar icon for Dokcer (bottom right) and not application running icon of docker (bottom) that needs the right click..

Thanks a lot, cant describe how much helpfull this was

**Comment by michihupf** [comment]
Any way to get the image to work on Linux? (sorry for the bump)
