### ISSUE TITLE
Create a PowerShell module to replace Build.ps1 and its multiple features

### ISSUE THREAD

**Issue by jeanfrancoislarente** [Sitecore/docker-images#17]
We should modify the Find-SitecoreVersions function in Build.ps1 script to do just that, simply find the versions.

Would be another breaking change - but it's still early on in the adoption of the source.

Best approach is probably to remove Build.ps1, create a PSM1 file and follow PS best practices for creating Approved Verb Functions?

Thoughts are appreciated.  @pbering ?

**Comment by pbering** [comment]
I think this is a good idea, especially now with the new additional helper script CheckSources.ps1.

**Comment by Ben-m-s** [comment]
I agree

**Comment by Ben-m-s** [comment]
The Build process is already implemented as a PowerShell module. The latest changes made on the PR #29, add the required explanations to find and the images versions and to check its required assets so that typical issues can be easily prevented before building the images.
