### ISSUE TITLE
Sitecore XP 9.2 | Identity server  image configuration is missing| Sync between local machine and docker machine 

### ISSUE THREAD

**Issue by VipraB** [Sitecore/docker-images#185]
Question1 
Post installation of XP 9.2.0 standalone the Identity server website was not created and CM login url was as per older version of Sitecore.(Sitecore 9 or 8.2).
In the current images found in https://github.com/Sitecore/docker-images/blob/master/windows/tests/9.2.x/docker-compose.xp.spe.yml we donot see an identity server images and corresponding linking to the required roles.

We currently want to use identity server as part of our setup .Please suggest the updates to the compose file to use it.

Question 2
For code and configuration deployment on corresponding sitecore website could you please suggest how can we configure syncing between local machine and the docker container

**Comment by pbering** [comment]
Q1: You should be able to do the same as in XC: https://github.com/Sitecore/docker-images/blob/master/windows/tests/9.2.x/docker-compose.xc.yml and re-enable Identity Server by renaming/deleting the file: C:\\inetpub\\wwwroot\\App_Config\\Include\\Sitecore.Owin.Authentication.IdentityServer.Disabler.config

Q2: Use the new optional ENTRYPOINT script: https://github.com/Sitecore/docker-images#optional-entrypoint-scripts, it will also start the Watch-Directory.ps1 script that syncs files from C:\src into the IIS site that is running Sitecore.

**Comment by pbering** [comment]
@VipraB I will close this issue for now, you can also join the #Docker channel on Sitecore Slack for questions :)
