### ISSUE TITLE
Could not resolve host error when building 9.2 sql image

### ISSUE THREAD

**Issue by Barsonax** [Sitecore/docker-images#186]
Seems like some url was changed on the microsoft side?

```
Step 5/8 : RUN New-Item -Path 'C:\\install' -ItemType 'Directory' | Out-Null;     curl.exe -sS -L -o C:\\install\\SQL.exe 'https://go.microsoft.com/fwlink/?linkid=840945';     curl.exe -sS -L -o C:\\install\\SQL.box 'https://go.microsoft.com/fwlink/?linkid=840944';     Start-Process -FilePath 'C:\\install\\SQL.exe' -ArgumentList '/qs', '/x:C:\install\setup' -NoNewWindow -Wait;     Start-Process -FilePath 'C:\\install\\setup\\setup.exe' -ArgumentList '/q', '/ACTION=Install', '/INSTANCENAME=MSSQLSERVER', '/FEATURES=SQLEngine', '/UPDATEENABLED=0', '/SQLSVCACCOUNT=\"NT AUTHORITY\System\"', '/SQLSYSADMINACCOUNTS=\"BUILTIN\ADMINISTRATORS\"', '/TCPENABLED=1', '/NPENABLED=0', '/IACCEPTSQLSERVERLICENSETERMS' -NoNewWindow -Wait;     Stop-Service MSSQLSERVER;     Set-ItemProperty -Path 'HKLM:\software\microsoft\microsoft sql server\mssql14.MSSQLSERVER\mssqlserver\supersocketnetlib\tcp\ipall' -Name 'tcpdynamicports' -Value '';     Set-ItemProperty -Path 'HKLM:\software\microsoft\microsoft sql server\mssql14.MSSQLSERVER\mssqlserver\supersocketnetlib\tcp\ipall' -Name 'tcpport' -Value 1433;     Set-ItemProperty -Path 'HKLM:\software\microsoft\microsoft sql server\mssql14.MSSQLSERVER\mssqlserver' -Name 'LoginMode' -Value 2;     curl.exe -sS -L -o C:\\install\\DacFramework.msi 'https://download.microsoft.com/download/9/2/2/9228AAC2-90D1-4F48-B423-AF345296C7DD/EN/x64/DacFramework.msi';     Start-Process -FilePath 'msiexec.exe' -ArgumentList '/i', 'C:\\install\\DacFramework.msi', '/quiet', '/norestart' -NoNewWindow -Wait;     Remove-Item -Path 'C:\\install' -Recurse -Force;
 ---> Running in 8402e8b9e023
curl: (6) Could not resolve host: go.microsoft.com
```

EDIT: only happens on the wifi, it can resolve the hostname though but its just too slow so it probably just timeouts?

**Comment by pbering** [comment]
Can't seem to reproduce here. Can you try:

```
docker run --rm mcr.microsoft.com/windows/servercore:ltcurl.exe -I https://go.microsoft.com/fwlink/?linkid=840944
```

which should give you:

```
HTTP/1.1 302 Moved Temporarily
Content-Length: 0
Location: http://download.microsoft.com/download/E/F/2/EF23C21D-7860-4F05-88CE-39AA114B014B/SQLServer2017-DEV-x64-ENU.box
```

If not, and it the curl command works on your host, then you have a network issue inside docker. You can try to run `docker network prune --force` to resolve it. Still not working, try to uninstall Hyper-V and remove all Hyper-V network adapters through the Device Manager, reboot and install Hyper-V again.

**Comment by Barsonax** [comment]
It was a network issue so this issue can be closed. Still annoying though that it only works if I use the ethernet cable and not the wifi (unless I cleanup everything) but thats not the responsibility of this repo.

**Comment by pbering** [comment]
Thanks for the feedback, regarding your ethernet / wifi issues you can fix that by ensuring that the interface that gives you internet has the lowest interface metric, check with `Get-NetIPInterface -AddressFamily IPv4 | Sort-Object -Property InterfaceMetric -Descending` and then set with `Set-NetIPInterface -InterfaceAlias 'Ethernet 2' -InterfaceMetric 10` (example values)

**Comment by moo2u2** [comment]
Had the same issue, and fixed it by adding custom DNS entry to Docker daemon.json (or in Docker settings window)
eg. using Google's: `"dns": ["8.8.8.8"]`
