### ISSUE TITLE
`sitecore-openjdk` images are no longer built

### ISSUE THREAD

**Issue by sshushliapin** [Sitecore/docker-images#187]
I use tags as specified in the examples (e.g. `$tags = "*:9.3.0*1903"`). One of my very new build agents is unable to build images failing with the following error:

```
docker : pull access denied for sitecore-openjdk, repository does not exist or may require  
'docker login': denied: requested access to the resource is denied
```

It appeared that `sitecore-openjdk` image is _missing_ and is excluded from the list of images to build:

```
sitecore-openjdk:8-nanoserver-1809                                       False      False        2 {mcr.microsoft.co...
sitecore-openjdk:8-nanoserver-1903                                       False      False        2 {mcr.microsoft.co...
sitecore-openjdk:8-nanoserver-1909                                       False      False        2 {mcr.microsoft.co...
```

The latest openjdk version I have in my repo is from Dec 18th. Could it be that PR #175 caused the issue?

**Comment by pbering** [comment]
this is interesting...  if I run this from current master:

```
SitecoreImageBuilder\Invoke-Build `
    -Path (Join-Path $PSScriptRoot "\windows") `
    -InstallSourcePath $installSourcePath `
    -Tags "*:9.3.0*1903" `
    -Verbose `
    -WhatIf:$true
```

With PowerShell Core (v6.x) I get openjdk included but if I run with PowersShell Classic (v5) I it is not included. I will look into to this.

**Comment by pbering** [comment]
Found it the problem and PR #188 fixes this. Thanks for reporting :)
