### ISSUE TITLE
Managing the IIS server in Sitecore XP docker image

### ISSUE THREAD

**Issue by VipraB** [Sitecore/docker-images#193]
If we have to manage IIS for the hosted website like setting binding properties installing certificates.

**Comment by pbering** [comment]
Is this a question? if so... normally you don't manage the IIS site inside the container, you have a reverse proxy container in front of it, that can for example rewrite hostnames and manage SSL (which is terminated on it's way to the Sitecore containers). Example: https://github.com/pbering/sitecore-docker-https-example.

**Comment by pbering** [comment]
@VipraB I will close this issue for now, you can also join the #Docker channel on Sitecore Slack for questions :)
