### ISSUE TITLE
Assertion failed: Target 'XpXconnect' requires 'Exists(Convert((Build.Files / value(Build).XCONNECT_PACKAGE), String))'

### ISSUE THREAD

**Issue by spiraljacobs** [Sitecore/docker-images#196]
When running build.ps1, i receive this error:

_  _ _  _ _  _ ____
|\ | |  | |_/  |___
| \| |__| | \_ |___

Assertion failed: Target 'XpXconnect' requires 'Exists(Convert((Build.Files / value(Build).XCONNECT_PACKAGE), String))'.
   at Nuke.Common.ControlFlow.Fail(String text)
   at Nuke.Common.Execution.RequirementService.ValidateRequirements(NukeBuild build)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1 defaultTargetExpression)

Repeating warnings and errors:
Assertion failed: Target 'XpXconnect' requires 'Exists(Convert((Build.Files / value(Build).XCONNECT_PACKAGE), String))'.

==============================================
Target                    Status      Duration
----------------------------------------------
BaseSitecore              NotRun          0:00
XpXconnect                NotRun          0:00
BaseSolrBuilder           NotRun          0:00
BaseOpenJdk               NotRun          0:00
XpSolr                    NotRun          0:00
XpIdentity                NotRun          0:00
XpSitecore                NotRun          0:00
XpMssql                   NotRun          0:00
Xp                        NotRun          0:00
XpSitecoreMssqlJss        NotRun          0:00
XpJss                     NotRun          0:00
XpSolrSxa                 NotRun          0:00
XpSitecoreMssqlSxa        NotRun          0:00
XpSxa                     NotRun          0:00
XcIdentity                NotRun          0:00
XcXconnect                NotRun          0:00
XcSolr                    NotRun          0:00
XcSitecoreIntermediate    NotRun          0:00
XcMssqlIntermediate       NotRun          0:00
XcCommerce                NotRun          0:00
XcSitecoreMssql           NotRun          0:00
Xc                        NotRun          0:00
XcSitecoreMssqlJss        NotRun          0:00
XcJss                     NotRun          0:00
XcSolrSxa                 NotRun          0:00
XcSitecoreMssqlSxa        NotRun          0:00
XcSxa                     NotRun          0:00
All                       NotRun          0:00
----------------------------------------------
Total                                     0:00
==============================================

Build failed on 14/01/2020 13:18:44.

Any ideas?

**Comment by pbering** [comment]
Hi, we are not using Nuke in this repo, are you sure this issue belongs here? :)

**Comment by spiraljacobs** [comment]
Yep, i'm an idiot, was an old .ps1 in the same folder.  I have a legit question, but I'l just close this for now and open a new one...*sheepish*

**Comment by spiraljacobs** [comment]
Yep, i'm an idiot, was an old .ps1 in the same folder. I have a legit question, but I'l just close this for now and open a new one...sheepish
