### ISSUE TITLE
9.3.x xm Docker Compose Up stalls on Information Attempting to load library 'xplog70.dll' in...

### ISSUE THREAD

**Issue by spiraljacobs** [Sitecore/docker-images#201]
Hi there,

Images built fine, everything looks good, however, when I run windows\tests\9.3.x> docker-compose --file .\docker-compose.xm.yml up, it seems to stall out on 

Information Attempting to load library 'xplog70.dll' in...

**Comment by pbering** [comment]
hmm haven't seen this before. Is your machine low on memory? Try to check the docker log file at `%LOCALAPPDATA%\Docker\log.txt` and see if it has any clues...

**Comment by spiraljacobs** [comment]
@pbering must have been memory. I retried a few times, restarted a couple of times, and it's since got through very quickly.  
9.3 up and running!
thanks for the help!
