### ISSUE TITLE
Add progress details to build process

### ISSUE THREAD

**Issue by michaellwest** [Sitecore/docker-images#204]
Time each stage takes.

Total time for all builds.

Final report at the end on the completed builds.

**Note:** Moving the progress bar to another issue once I have a more solid solution.

**Comment by michaellwest** [comment]
Thinking something like this would prove helpful.

![image](https://user-images.githubusercontent.com/933163/72671064-8396bf00-3a0a-11ea-90ea-7aafd80b5695.png)

**Comment by pbering** [comment]
Agreed that it would be a nice addition to have. Please don't use "Write-Progress" for the progress part but keep it as clear text. Write-Progress is a performance killer when used in containers or build agent (everything attaching to the output streams). Even in the console you can see the problem:

```
for($i = 0; $i -lt 500000; ++$i)
{
  Write-Progress -Activity Test -Status "Done $i"
}
```

**Comment by pbering** [comment]
Could be very cool if we could do some kind of "progress writer" instance that could either be console (default as now) or Azure DevOps Pipeline adding progress as logging commands: https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#setprogress-show-percentage-completed and/or https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#logdetail-create-and-update-a-timeline-record-for-a-task. I know TeamCity as similar functionality that one could write a "progress writer" for.

**Comment by michaellwest** [comment]
This first commit adds time to the messages as well as a report at the end.

**Comment by michaellwest** [comment]
Thanks for the feedback @pbering . Moving the progress bar request to a new issue. The current change is already helpful.

**Comment by michaellwest** [comment]
This is now merged.
