### ISSUE TITLE
Could not build SXA images

### ISSUE THREAD

**Issue by Antonytm** [Sitecore/docker-images#207]
In order to try Sitecore\Sitecore.HabitatHome.Platform I want to build SXA images. But getting error during build.

**Steps to reproduce:**
1) Run 
`.\Build.ps1 -SitecoreUsername "XXX" -SitecorePassword "YYY" -Registry "localhost:5000" -IncludeSxa`
2) Wait for execution

**Expected result:** I should get Sitecore SXA images in local registry
**Actual result:** I get error.

> Failed: docker image build --isolation 'hyperv' --build-arg BASE_IMAGE=sitecore-xm-cd:9.3.0-windowsservercore-ltsc2019
> --build-arg ASSETS_IMAGE=sitecore-assets:9.3.0-nanoserver-1809 --build-arg ASSETS_USE_WDP='C:\packages\Sitecore
> Experience Accelerator 9.3.0.2589 CD.scwdp.zip' --tag 'sitecore-xm-sxa-cd:9.3.0-windowsservercore-ltsc2019'
> 'D:\Sources\docker-images\windows\9.x.x\sitecore-sxa'
> At D:\Sources\docker-images\modules\SitecoreImageBuilder\SitecoreImageBuilder.psm1:287 char:74
> \+ ... here-Object { $_ } | ForEach-Object { throw "Failed: $buildCommand" }
> \+                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     \+ CategoryInfo          : OperationStopped: (Failed: docker ...x\sitecore-sxa':String) [], RuntimeException
>     \+ FullyQualifiedErrorId : Failed: docker image build --isolation 'hyperv' --build-arg BASE_IMAGE=sitecore-xm-cd:9.
>    3.0-windowsservercore-ltsc2019 --build-arg ASSETS_IMAGE=sitecore-assets:9.3.0-nanoserver-1809 --build-arg ASSETS_U
>   SE_WDP='C:\packages\Sitecore Experience Accelerator 9.3.0.2589 CD.scwdp.zip' --tag 'sitecore-xm-sxa-cd:9.3.0-windo
>  wsservercore-ltsc2019' 'D:\Sources\docker-images\windows\9.x.x\sitecore-sxa'

![image](https://user-images.githubusercontent.com/647813/72701807-3b39e700-3b59-11ea-8f95-6ec8e89d5a72.png)

I was able to reproduce this issue is on 2 different machines.

**Comment by pbering** [comment]
Hi, there is currently some issue in Windows causing this to happen, seems to have started late November, see comment https://github.com/Sitecore/docker-images/issues/189#issuecomment-573401441 for a workaround.
