### ISSUE TITLE
PublishingService.UrlRoot not set in SXA-PS CM image

### ISSUE THREAD

**Issue by bplasmeijer** [Sitecore/docker-images#208]
![image](https://user-images.githubusercontent.com/116467/72726906-dba7ff80-3b89-11ea-8441-c7fdffebe61e.png)

**Comment by bplasmeijer** [comment]
- Update Sitecore.Publishing.Service.config

**Comment by peternazarov** [comment]
The workaround: https://www.slideshare.net/pnazarov/sitecore-docker-xmxp-920930-sxajssps/9

**Comment by sshushliapin** [comment]
Fixed in #275. Can be closed.
