### ISSUE TITLE
Add progress bar for package downloads

### ISSUE THREAD

**Issue by michaellwest** [Sitecore/docker-images#210]
The following request is to improve the developer experience when downloading packages.

![2020-01-20_22-20-43](https://user-images.githubusercontent.com/933163/72952322-157a3100-3d57-11ea-8b3b-a537db35df46.gif)

This has been tested in the PowerShell 5.1 Console and VSCode. The progress bar does not render for the PowerShell ISE due to limitations with the console.

**Comment by pbering** [comment]
I had to revert the merge of the PR since there is a problem when running on Azure DevOps Pipelines in PowerShell v5:

```
13:45:32:984: Downloading 'https://dev.sitecore.net/~/media/C1E7682DA9CD48B68FDE7DE9AB2E8419.ashx' to 'S:\Sitecore 9.2.0 rev. 002893 (WDP XM1 packages).zip'...
VERBOSE: 13:45:32:984: Logging in to 'https://dev.sitecore.net'...
VERBOSE: POST https://dev.sitecore.net/api/authorization with -1-byte payload
VERBOSE: received 4-byte response of content type application/json; charset=utf-8
VERBOSE: 13:45:41:486: Logged in to 'https://dev.sitecore.net'.
Write-InlineProgress : Exception setting "CursorVisible": "The handle is invalid.
"
At C:\vsts-agent\_work\1\s\modules\SitecoreImageBuilder\1.0.0\Private\Invoke-FileDownload.ps1:283 char:17
+ ...             Write-InlineProgress -Activity "Downloading" -PercentComp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-InlineProgress], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting,Write-InlineProgress

```

PowerShell 5 and Core 6 seems to work fine locally.

**Comment by michaellwest** [comment]
Was able to duplicate the issue.

![image](https://user-images.githubusercontent.com/933163/73086892-19ad6800-3e97-11ea-901b-65a281a52746.png)

**Comment by michaellwest** [comment]
Would this be acceptable?

![image](https://user-images.githubusercontent.com/933163/73088019-11eec300-3e99-11ea-94a6-6b556f5e9466.png)

**Comment by pbering** [comment]
Yeah that looks neat :)

**Comment by michaellwest** [comment]
The latest commit address an issue where "ConsoleHost" is the same for both Azure DevOps and the PowerShell Console on your local Windows. Decided the easiest check is to first validate that the Cursor values can be retrieved. If it works then you get the progress bar. If it fails it falls back to the one-line-per-update message.

**Comment by basselissa** [comment]
it is taking ages to have packages downloaded !. does anyone experienced the same?

**Comment by vincentlui-alinta** [comment]
Unfortunately that's a problem at Sitecore side. I manually download everything myself and put those on Azure File Share.

**Comment by michaellwest** [comment]
That's an issue due to how the packages are hosted by Sitecore. You can download the packages manually without using the Docker Image build scripts and still experience this.
