### ISSUE TITLE
Not able to build 9.2 XC after 9.3 XC was merged

### ISSUE THREAD

**Issue by pbering** [Sitecore/docker-images#235]
The dockerfiler is reused across 9.2 and 9.3 and it seems that new cores are introduced that 9.2 do not have: https://github.com/Sitecore/docker-images/commit/19d9997f5f8254680965838a4bf58d7a66acec83#diff-732638c8c312e7bbe929b2d2f5c021b4R63

**Comment by joostmeijles** [comment]
Ah indeed, I should have created a 9.3.x version.
