### ISSUE TITLE
Windows Blue Screen of Death - Running XC Solr container in `process` isolation

### ISSUE THREAD

**Issue by peternazarov** [Sitecore/docker-images#244]
Running Windows 1909 XC Solr container in `process` isolation causing Windows Blue Screen of Death when the container is stopped is made. Basically, every time the container is stopped you get Windows Blue Screen of Death. This quite a showstopper for development.

It only happens with XC `solr` container. All others XM and XP based `solr` containers do not have this issue.

![image](https://user-images.githubusercontent.com/21163169/74352950-8393a000-4db9-11ea-8622-6e93618fae35.png)

**Comment by peternazarov** [comment]
Workaround:

Set Solr container isolation to `hyperv`

Example:
```  solr:
    image: ${REGISTRY}sitecore-xc-solr:${SITECORE_VERSION}-nanoserver-${NANOSERVER_VERSION}
    volumes:
      - .\data\solr:C:\Data
    isolation: hyperv
    mem_limit: 1GB
    ports:
      - "44011:8983"```

**Comment by peternazarov** [comment]
Tried on `i7-6700HQ` equipped MSI laptop - there is no issue. 

The issue occurs on Dell Latitude 7490 with `i7-8650U`.

**Comment by joostmeijles** [comment]
@peternazarov this seems Docker for Windows related and solved. May this issue be closed?

**Comment by peternazarov** [comment]
Hi @joostmeijles 

I have updated Docker and tested it. The issue is solved. Please close this ticket.
