### ISSUE TITLE
SQLServer2017-DEV-x64-ENU.exe corrupted?

### ISSUE THREAD

**Issue by afortaleza** [Sitecore/docker-images#249]
Building `mssql-developer:2017-windowsservercore-1909` and getting the following error:

```powershell
Start-Process : This command cannot be run due to the error: The system cannot
find the file specified.
At line:1 char:429
+ ... ndow -Wait; Start-Process -FilePath 'C:\\install\\setup\\setup.exe' - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOp
   erationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.C
   ommands.StartProcessCommand
```

When downloading `SQLServer2017-DEV-x64-ENU.exe` and renaming it to `SQL.exe` in my host PC and running the command 
```powershell
Start-Process -FilePath 'C:\\install\\SQL.exe' -ArgumentList '/qs', '/x:C:\install\setup' -NoNewWindow -Wait
```
The command exits immediatly and the `C:\install\setup\setup.exe` file is not created and when I double click the `SQL.exe` file I get the following error message:

![image](https://user-images.githubusercontent.com/407682/74762421-9516f500-525c-11ea-932f-746783c1752b.png)

The `SHA256` hash for the `SQL.exe` file downloaded is `D7690A894740EE1464BD42AECE860ED4358E83D8AF347B60ED1AADFE7C580E05`.

Here's the requested from the Dockerfile
https://github.com/Sitecore/docker-images/blob/e1ea95da3d342417f15a1b186695f95e6f1d562e/windows/dependencies/mssql-developer-2017/Dockerfile#L14

I think the `SQLServer2017-DEV-x64-ENU.exe` was corrupted on Microsoft download servers.

**Comment by afortaleza** [comment]
The file is not corrupted, it had to be executed with the SQL.box file in the same directory, still I am getting the same error. Another colleague got the same error in a different continent.

**Comment by anarsen** [comment]
Experienced the exact same thing this morning on AWS EC2 instances running Windows Server Core 2019 (LTSC). Ran it again and again, and now I'm getting this error message instead:

```text
Start-Process : Cannot process request because the process (3876) has exited.
At line:1 char:319
+ ... id=840944'; Start-Process -FilePath 'C:\\install\\SQL.exe' -ArgumentL ...
```

It works on my local workstation though.

I'll keep you posted if I figure something out.

**Comment by mquekel** [comment]
I have the same issue. Could it be related to the Windows Update issues? 
https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t

**Comment by anarsen** [comment]
> I have the same issue. Could it be related to the Windows Update issues?
> https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t

That was indeed the case! I have to pay way more attention to the version parity between host and container OS. Thank you for the pointer.
