### ISSUE TITLE
Question: Using the code in the 'develop' branch for Sitecore development

### ISSUE THREAD

**Issue by petermarnef** [Sitecore/docker-images#25]
Hi,

The code on the develop branch seems to be working fine. And although I have not used it with our own solution, the demo from the docker-demo repo is working on my machine. But before we move on to our own solution, I see the develop branch has been sitting idle for a while, and was wondering if it's a good idea to base our Sitecore/Docker development efforts on this repo? The alternative is we build our own setup, but this takes time and I rather like the idea of using a central repo that is supported by the community.

Fyi: we're a small development team that is experimenting with docker, and would like to use a docker setup initially for local development only. Possibly moving onto other environments, when our local setup is stable.

**Comment by jeanfrancoislarente** [comment]
Hello @petermarnef 
The original purpose for this repo was to bring folks together to a centralized location.
I know @Ben-m-s and others have invested a LOT of time on this repo. It has been forked 20 times and starred 40 times - not sure what that means, but I know there are definitely people looking at this repo.

If more folks used this as their attempts it would make this repo more active. I also know @pbering maintains a separate repo. 

I may be wrong but this is one of the few repos that tackles XP as well as XM. As always when using Open Source repos, and particularly in this case, Sitecore doesn't provide official support for Docker yet so any attempts at running Sitecore in containers is at your own risk without the support of Sitecore.

**Comment by jeanfrancoislarente** [comment]
merged latest develop to master.
