### ISSUE TITLE
Docker: 'image' is not a docker command.

### ISSUE THREAD

**Issue by aiorgu** [Sitecore/docker-images#250]
`14:03:09:438: Build specifications loaded...
docker: 'image' is not a docker command.
See 'docker --help'.
Failed.
At D:\ScDocker\docker-images\modules\SitecoreImageBuilder\1.0.0\Public\Invoke-Build.ps1:111 char:78`

Hey guys. I've been trying to run the installer and ran into this issue on the latest code.

Managed to fix this issue by removing the **images** tag from **Invoke-Build.ps1** on line 111 

`docker image pull $tag`

**Comment by pbering** [comment]
What is the output of `docker --version` and `get-command docker`? Sounds like you have a very old version of the docker cli...

**Comment by aiorgu** [comment]
Just installed today, the latest version from https://www.docker.com/products/docker-desktop

`Docker version 1.12.0-dev, build 8e92415 `
 
`Application     docker.exe                                         1.12.0.0   C:\WINDOWS\system32\docker.exe`

Thank you for the fast reaction

**Comment by pbering** [comment]
Seems you have a very old version installed in `C:\Windows\System32\docker.exe`, delete that and then I guess the right version will be used which is `C:\Program Files\Docker\Docker\resources\bin\docker.exe` (installed with Docker Desktop)

**Comment by aiorgu** [comment]
Thank you, this fixed my issue
