### ISSUE TITLE
Invoke-Build.ps1 fails on Windows 2016 with Docker Enterprise installed

### ISSUE THREAD

**Issue by viccan** [Sitecore/docker-images#255]
When I run:
.\Build.ps1 -SitecoreUsername "username" -SitecorePassword "xxxxxxx"

it goes fine until fails here:

17:20:26:169: Build specifications loaded...
ltsc2019: Pulling from windows/servercore
no matching manifest for windows/amd64 10.0.14393 in the manifest list entries
Failed.
At C:\Users\stoyan\Documents\GitHub\docker-images\modules\SitecoreImageBuilder\1.0.0\Public\Invoke-Build.ps1:111 char:78
+ ... CODE -ne 0 | Where-Object { $_ } | ForEach-Object { throw "Failed." }
+                                                         ~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed.

I'm trying to configure everything on brand new Azure VM with Windows 2016 Datacenter.
Any ideas?

**Comment by pbering** [comment]
2016 server is way too old, you need at least 2019 LTSC.

**Comment by pbering** [comment]
I will close this for now.
