### ISSUE TITLE
How to check Sitecore running role?

### ISSUE THREAD

**Issue by mitikov** [Sitecore/docker-images#264]
It seem platform lacks a mechanism to verify the running role, that is an error-prone path:

1. Define SITECORE_APPSETTING_ROLE:DEFINE: **Standalone** for CM
2. Start docker, like xm topology
3. Login to Sitecore Shell
4. Sitecore -> All Apps -> Run -> File Explorer 
5. Download web.config

**Expected result**: role is set to `Standalone` per 1st step

**Actual result**: role is set to `ContentManagement, Indexing` 

The first step has a typo around AppSetting**s** that is difficult to spot; as web.config gets overridden via appSettings inMemory you do not trust it any longer (even though it is right now).

Neither `Showconfig`, nor `ShowConfigLayers` AFAIK show running role =\

Am I missing anything?

Thanks.

**Comment by mitikov** [comment]
The solution could be to add hand-written Sitecore config that will append dummy values to config based on roles (sample):

```
<role:require="standalone"/>

<setting name="Standalone" value="true/>

....
```

Do we wanna follow that approach?

**Comment by pbering** [comment]
I can't see the values injected with environment variables, they are not persisted in the files but injected at runtime. The reason why you see `ContentManagement, Indexing` (same as we set in compose for demo purposes) is that it is the default value for an XM CM set in the Web.config from the source WDP.

**Comment by mitikov** [comment]
So true. 

Is it fair to say there is no way to check if env.variable has been picked by Sitecore correctly now?

**Comment by pbering** [comment]
ahh not entirely true :) ... depends on what you mean by "no way to check"... you could do something like this since the role is set correctly at runtime:

```
<setting name="Standalone" role:require="Standalone" value="true/>    
```

you can also read it from appSettings["role:define"] if you want.

**Comment by mitikov** [comment]
Yup, that is exactly my point - there is no such mechanism OOB: we need cook dummy-settings that will show role.

**Comment by pbering** [comment]
I'm not sure how this is different from running Sitecore outside of Docker?

**Comment by jeanfrancoislarente** [comment]
I just went through this internally with the product team. Doesn't look like anything is exposed in Sitecore to say "what-is-my-role".

We solved it by doing what @pbering suggested by reading the Configuration.

**Comment by mitikov** [comment]
Glad to hear @pbering advise is same as [the solution I've suggested](https://github.com/Sitecore/docker-images/issues/264#issuecomment-596401129). 

Will it be included into product, or must be manually hand-backed for every project?

Thanks.

**Comment by jeanfrancoislarente** [comment]
So, not quite the same as either of you, wouldn't this give you the right answer as configured?

```
var role = System.Configuration.ConfigurationManager.AppSettings["role:define"];
if (!role.Contains("ContentManagement"))
```

**Comment by pbering** [comment]
Yes, exactly what I meant with "...you can also read it from appSettings["role:define"] if you want."

**Comment by jeanfrancoislarente** [comment]
Not something that can be resolved in this repository

**Comment by mitikov** [comment]
There is a bug in platform so that env.variables are not applied: 

https://making-it-faster.blog/2020/03/22/do-not-trust-configuration/

JFYI.

**Comment by jballe** [comment]
> There is a bug in platform so that env.variables are not applied:
> 
> https://making-it-faster.blog/2020/03/22/do-not-trust-configuration/

Regarding completely new app settings, I think it is more of a design choice in the Microsoft Configuration Builders - but of course important to be aware of when you start adding your own settings.
