### ISSUE TITLE
Build Error on X-Connect Steps 12/19

### ISSUE THREAD

**Issue by raseniero** [Sitecore/docker-images#274]
Hi 

I'm getting this error when building it on **Step 12/19**: I'm windows 10 Version 1909

"]
 ---> Running in d9f50b092dd8
Removing intermediate container d9f50b092dd8
 ---> 1fe301c04fa4
Step 6/19 : ARG ASSETS_USE_WDP
 ---> Running in a08bce8978e4
Removing intermediate container a08bce8978e4
 ---> ea092c5b8715
Step 7/19 : ARG SC_ROLE_NAME
 ---> Running in 3d2d0195ea46
Removing intermediate container 3d2d0195ea46
 ---> c6eabdf737ec
Step 8/19 : COPY --from=assets ["${ASSETS_USE_WDP}", "C:\\temp\\packages\\"]
 ---> 91e331df236f
Step 9/19 : RUN Expand-Archive -Path 'C:\\temp\\packages\\*.zip' -DestinationPath 'C:\\temp';     New-Item -Path 'C:\\worker' -ItemType Directory | Out-Null;     Copy-Item -Path ('C:\\temp\\Content\\Website\\App_Data\\jobs\\continuous\\{0}\\*' -f $env:SC_ROLE_NAME) -Destination 'C:\\worker' -Recurse -Force;
 ---> Running in b7927dec17a8
Removing intermediate container b7927dec17a8
 ---> 8daef4c14812
Step 10/19 : COPY --from=assets ["C:\\install\\tools\\", "C:\\worker\\temp\\install\\tools\\"]
 ---> e41b8c4842fc
Step 11/19 : COPY .\\config\\ C:\\worker\\
 ---> 4e400d3e6839
Step 12/19 : RUN $xdts = [System.Collections.ArrayList]@();     $xdts.AddRange(@(Get-ChildItem -Path 'C:\\worker\\App_Config\\*.xdt' -Recurse));     $xdts.AddRange(@(Get-ChildItem -Path 'C:\\worker\\App_Data\\Config\\*.xdt' -Recurse));     $xdts | ForEach-Object { & 'C:\\worker\\temp\\install\\tools\\scripts\\Invoke-XdtTransform.ps1' -Path $_.FullName.Replace('.xdt', '') -XdtPath $_.FullName -XdtDllPath 'C:\\worker\\temp\\install\\tools\\bin\\Microsoft.Web.XmlTransform.dll'; };     $xdts | ForEach-Object { Remove-Item -Path $_.FullName; };
 ---> Running in 59bef19ef487
container 59bef19ef48754fbe559ba735349e8ec6b3486aa0a74cd5a90cbd3587e1cf14e encountered an error during hcsshim::System::Start: context deadline exceeded
Failed: docker image build --isolation 'hyperv' --build-arg
BASE_IMAGE=mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019 --build-arg
ASSETS_IMAGE=sitecore-assets:9.3.0-nanoserver-1809 --build-arg ASSETS_USE_WDP='C:\packages\Sitecore 9.3.0
(OnPrem)_xp0xconnect.scwdp.zip' --build-arg SC_ROLE_NAME=IndexWorker --build-arg
SC_ROLE_EXE=Sitecore.XConnectSearchIndexer.exe --tag
'sitecore-xp-xconnect-indexworker:9.3.0-windowsservercore-ltsc2019'
'C:\Projects\docker-images\windows\9.3.x\sitecore-xp-xconnect-worker'
At C:\Projects\docker-images\modules\SitecoreImageBuilder\1.0.0\Public\Invoke-Build.ps1:219 char:74
+ ... here-Object { $_ } | ForEach-Object { throw "Failed: $buildCommand" }
+                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed: docker ...connect-worker':String) [], RuntimeException
    + FullyQualifiedErrorId : Failed: docker image build --isolation 'hyperv' --build-arg BASE_IMAGE=mcr.microsoft.com
   /dotnet/framework/runtime:4.8-windowsservercore-ltsc2019 --build-arg ASSETS_IMAGE=sitecore-assets:9.3.0-nanoserver
  -1809 --build-arg ASSETS_USE_WDP='C:\packages\Sitecore 9.3.0 (OnPrem)_xp0xconnect.scwdp.zip' --build-arg SC_ROLE_N
 AME=IndexWorker --build-arg SC_ROLE_EXE=Sitecore.XConnectSearchIndexer.exe --tag 'sitecore-xp-xconnect-indexworker
:9.3.0-windowsservercore-ltsc2019' 'C:\Projects\docker-images\windows\9.3.x\sitecore-xp-xconnect-worker'

Thanks,
Ramon

**Comment by bplasmeijer** [comment]
please provide .\build.ps1 ...... args

**Comment by pbering** [comment]
Closed due to inactivity, please reopen new issue if you still are having problems,
