### ISSUE TITLE
Artifacts not cleaned up correctly on sitecore-xc-sxa-storefront-sqldev

### ISSUE THREAD

**Issue by jeanfrancoislarente** [Sitecore/docker-images#277]
`INSTALL_MODULE_PATH` still contained WDPs after the completion of the build.

Looks like the `-Include "*.*"` didn't have the intended behavior.

Need to change it to simply 
`Get-ChildItem -Path $env:INSTALL_MODULE_PATH | Remove-Item -Force -Recurse;`

**Comment by bplasmeijer** [comment]
merged #265
