### ISSUE TITLE
Publish service not being build after following instructions

### ISSUE THREAD

**Issue by Barsonax** [Sitecore/docker-images#284]
After following the instructions in the readme https://github.com/Sitecore/docker-images#experimental-publishing-service-not-automatically-build-because-of-missing-prerequisites-from-sitecore iam not seeing a publish service image being build. It seems it only prepares the prerequisites. Is there still something missing in the readme or is this the reason its still experimental?

**Comment by sshushliapin** [comment]
Readme looks ok to me. I managed to build images, but faced issue #262 (currently building from my fork until #273 and #275 are merged). Probably you need to provide more details about your environment (which scripts and which parameters are used). Otherwise it's hard to say what's wrong.

**Comment by Barsonax** [comment]
The build completes successfully but I would expect a publish service image to be build. You do get this image?

**Comment by sshushliapin** [comment]
Publishing service is for 9.3 ATM.

**Comment by Barsonax** [comment]
Thats a bummer, are there plans to make it available on older versions as well in the future?

**Comment by pbering** [comment]
No current plans as I know of, sorry. But please feel free to make them in a PR and references this issue.

**Comment by pbering** [comment]
Closing this one for now.
