### ISSUE TITLE
docker-compose -f docker-compose.xp.yml up FAILED

### ISSUE THREAD

**Issue by vincentvc168** [Sitecore/docker-images#286]
PS C:\ScDocker\docker-images\windows\tests\9.3.x> docker-compose -f docker-compose.xp.yml up
Starting 93x_sql_1 ...
Starting 93x_solr_1 ... error                                                                                           
Starting 93x_sql_1  ... error                                                                                           88 not found

ERROR: for 93x_sql_1  Cannot start service sql: network 3b44f38ab13096a488a37d31aa4d33a06d777d0c9ef236f2372c3ef9ce052e88 not found

ERROR: for solr  Cannot start service solr: network 3b44f38ab13096a488a37d31aa4d33a06d777d0c9ef236f2372c3ef9ce052e88 not found

ERROR: for sql  Cannot start service sql: network 3b44f38ab13096a488a37d31aa4d33a06d777d0c9ef236f2372c3ef9ce052e88 not found
ERROR: Encountered errors while bringing up the project.

**Comment by GurliGebis** [comment]
Do a docker-compose down, and then try again. Windows does not persist networks across reboots.
