### ISSUE TITLE
Content-Security-Policy is removed in 9.3.x images

### ISSUE THREAD

**Issue by vitaliitylyk** [Sitecore/docker-images#288]
I have noticed that CSP policy header is completely removed in https://github.com/Sitecore/docker-images/blob/master/windows/9.3.x/sitecore-xm/config/cm/Web.config.xdt via `<add name="Content-Security-Policy" xdt:Locator="Match(name)" xdt:Transform="Remove" />`

As far as I understand the reason is this part: `upgrade-insecure-requests; block-all-mixed-content;` which can cause login issues when not using `HTTPS`. However, the rest of the CSP header is still useful. 

I suggest to keep the header and remove only `upgrade-insecure-requests; block-all-mixed-content;`, what do you think? This will make CM more secure by default.

**Comment by pbering** [comment]
I agree that it would be better to only remove `upgrade-insecure-requests; block-all-mixed-content` and keep the rest.

**Comment by vitaliitylyk** [comment]
Alright, I will submit a PR then
