### ISSUE TITLE
[Win32Exception (0x80004005): The network path was not found], and Solr is not showing

### ISSUE THREAD

**Issue by basselissa** [Sitecore/docker-images#290]
Hi, 
tried to compose xm.yaml for 9.0.2 and images loaded well. but noticed that the solr listed when i try to list the "docker ps". tried to clean up and run again. the same, only CD/CM/SQL are up
and also i am not able to run any of the CM or CD as they are not reaching the sql instance
with the error :[Win32Exception (0x80004005): The network path was not found]. 

note that i am not using the External:nat here.  i have removed all the network lines from the yaml file.

**Comment by basselissa** [comment]
oh, later i found that even the sql disappeared from the "docker ps" list while it was showing a minute ago.

**Comment by basselissa** [comment]
i was able to verbos out the errors

this is what stop the Solr
solr_1  | "### Preparing Solr cores..."
solr_1  | Could Not Find c:\data\write.lock
solr_1  | "### Starting Solr..."
solr_1  |
solr_1  | ERROR: Java 1.8 or later is required to run Solr. Current Java version is:

and here are the error for SQL

l_1   | 15:50:40:582: Attaching 'Sitecore.Core'...
sql_1   | Invoke-Sqlcmd : A network-related or instance-specific error occurred while
sql_1   | establishing a connection to SQL Server. The server was not found or was not
sql_1   | accessible. Verify that the instance name is correct and that SQL Server is
sql_1   | configured to allow remote connections. (provider: Named Pipes Provider,
sql_1   | error: 40 - Could not open a connection to SQL Server)
sql_1   | At C:\Boot.ps1:36 char:5
sql_1   | +     Invoke-Sqlcmd -Query $sqlcmd
sql_1   | +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sql_1   |     + CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlExcept
sql_1   |    ion
sql_1   |     + FullyQualifiedErrorId : SqlExectionError,Microsoft.SqlServer.Management.
sql_1   |    PowerShell.GetScriptCommand

**Comment by basselissa** [comment]
So, do we have to have Java 1.8 installed on the host machine? !!

**Comment by pbering** [comment]
No need for having Java installed.

It seems that you have multiple problems with Docker and not images. Can you tell me which Windows version you are running? What is the output of `docker info`?

Lastly, can you run a simple IIS container with `docker container run -p 7777:80 mcr.microsoft.com/windows/servercore/iis` and then access localhost:7777 using your browser?

**Comment by pbering** [comment]
Can you please try again, your issue looks like #312 which we just merged a fix for.

**Comment by pbering** [comment]
Closing this one for now, please create new issue with you still have problems after trying #312
