### ISSUE TITLE
Sitecore XC version 9.3 - No Habitat catalog is present under /sitecore/Commerce/Catalog Management/

### ISSUE THREAD

**Issue by viethoangpyco** [Sitecore/docker-images#293]
Hi team,

> **The problematic OS versions: 1903 and 1909**

I'm managing to run XC with SPE & SXA & SXA Storefront by executing **docker-compose -f docker-compose.xc.sxa.storefront.yml up** and doing all the steps are mentioned in https://github.com/Sitecore/docker-images/blob/master/windows/tests/9.3.x/README.md successfully

I can access **Business Tools** http://bizfx and then see Habitat catalog (**Sitecore Identity Server** https://identity/ works properly in this case)
![image](https://user-images.githubusercontent.com/6151021/79682955-c312b880-8250-11ea-9d60-a050e68a8dad.png)

However, there is no Habitat catalog is present under /sitecore/Commerce/Catalog Management/
![image](https://user-images.githubusercontent.com/6151021/79682982-f6554780-8250-11ea-97ee-aaa6ee87312b.png)

There is an error message in Sitecore log **"The Sitecore Identity Server URL is invalid or missing from your configuration, secure communication with the Commerce Engine is not possible."**, for examples
![xc_catalog](https://user-images.githubusercontent.com/6151021/79683082-b478d100-8251-11ea-9b5b-5e32d373dccd.png)

**Comment by joostmeijles** [comment]
@viethoangpyco just to be sure; are you using a clean setup (e.g. no modifications in the Y.Commerce.Engine config dir)?

**Comment by viethoangpyco** [comment]
@joostmeijles thanks for your question. I just cleaned up everything and then pulled the latest code from **master** branch + built Sitecore images with Windows version **1909**. Wow, it works properly for me this time.

Let me give Windows version **1903** a shot as well.

**Comment by viethoangpyco** [comment]
@joostmeijles FYI it works properly for me on Windows version **1903** as well so I'm gonna close this issue. Anyway, thanks for your time :)
