### ISSUE TITLE
How to get started quicker without needing to wait 24h for the sitecore packages to download

### ISSUE THREAD

**Issue by markgibbons25** [Sitecore/docker-images#294]
I would like to be able to specify the exact packages that I would like to use so that I do not need to download the whole of dev.sitecore.net which goes at approx 25KB/s in Australia (This is a long term issue that I've raised with support to no avail)

![image](https://user-images.githubusercontent.com/3212534/80176303-77d71c00-863b-11ea-87a7-4c8b84a2e436.png)

Looks like I can edit the sitecore-packages.json and IMAGES.md but I'm a bit lost already. I just want to install Sitecore 9.3 XP0 with SXA and JSS.

Any guidance for a workaround, as well as a longer-term way of managing this for my colleagues who will no doubt have this issue?

**Comment by pbering** [comment]
Hi man, sorry about your download speeds, no fun!

You can parse in a array of tags to `SitecoreImageBuilder\Invoke-PackageRestore` and `SitecoreImageBuilder\Invoke-Build`, for example:

```
SitecoreImageBuilder\Invoke-PackageRestore `
    -Path (Join-Path $PSScriptRoot "\windows") `
    -Destination $installSourcePath `
    -Tags "*xp*:9.3.0*ltsc2019", "*xp*:9.3.0*1809" `
    -SitecoreUsername $sitecoreUsername `
    -SitecorePassword $sitecorePassword `
    -DeprecatedTagsBehavior "Skip"
```

**Comment by markgibbons25** [comment]
Thanks for the help, but its still trying to download XM (and failing)

> 04:42:30:732: Excluding experimental images.
> 04:42:30:816: The following images will be built:
> mssql-developer:2017-windowsservercore-1909
> sitecore-openjdk:8-nanoserver-1909
> sitecore-certificates:latest-nanoserver-1909
> sitecore-assets:9.3.0-nanoserver-1909
> sitecore-xp-standalone:9.3.0-windowsservercore-1909
> sitecore-xp-cd:9.3.0-windowsservercore-1909
> sitecore-xp-identity:9.3.0-windowsservercore-1909
> sitecore-xp-sqldev:9.3.0-windowsservercore-1909
> sitecore-xp-xconnect:9.3.0-windowsservercore-1909
> sitecore-xp-xconnect-indexworker:9.3.0-windowsservercore-1909
> sitecore-xp-xconnect-processingengine:9.3.0-windowsservercore-1909
> sitecore-xp-xconnect-automationengine:9.3.0-windowsservercore-1909
> sitecore-xp-solr:9.3.0-nanoserver-1909
> sitecore-xp-spe-standalone:9.3.0-windowsservercore-1909
> sitecore-xp-spe-sqldev:9.3.0-windowsservercore-1909
> sitecore-xp-sxa-standalone:9.3.0-windowsservercore-1909
> sitecore-xp-sxa-cd:9.3.0-windowsservercore-1909
> sitecore-xp-sxa-jss-standalone:9.3.0-windowsservercore-1909
> sitecore-xp-sxa-jss-cd:9.3.0-windowsservercore-1909
> sitecore-xp-sxa-jss-sqldev:9.3.0-windowsservercore-1909
> sitecore-xp-sxa-sqldev:9.3.0-windowsservercore-1909
> sitecore-xp-sxa-solr:9.3.0-nanoserver-1909
> sitecore-xp-jss-standalone:9.3.0-windowsservercore-1909
> sitecore-xp-jss-cd:9.3.0-windowsservercore-1909
> sitecore-xp-jss-sqldev:9.3.0-windowsservercore-1909
> 04:42:32:063: Downloading 'https://dev.sitecore.net/~/media/D1F694E4238C438B8464FC1ABFF06C87.ashx' to '.\packages\Sitecore 9.3.0 rev. 003498 (WDP XM1 packages).zip'...
> Invoke-FileDownload : The variable '$fileStream' cannot be retrieved because it has not been set.
> At C:\git\docker-images\modules\SitecoreImageBuilder\1.0.0\Public\Invoke-PackageRestore.ps1:128 char:21
> + ...             Invoke-FileDownload -Url $fileUrl -Path $filePath -Cookie ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (fileStream:String) [Invoke-FileDownload], RuntimeException
>     + FullyQualifiedErrorId : VariableIsUndefined,Invoke-FileDownload

**Comment by anarsen** [comment]
In my client's setup, we store the Sitecore packages in our own (private) blob storage and fetch it from there inside the pipeline.

After that we call `Invoke-Build` which will verify if the Sitecore packages match what's expected.

Mentioning it in case you want to do the same thing. Probably puts a lot less load on dev.sitecore.net for everyone else too.

**Comment by pbering** [comment]
yes, the asset image for 9.3 will download everything for 9.3 and reused across the different typologies and variants. Do you still have issues downloading? You can set the `$installSourcePath` to your path with all the packages pre-downloaded (for example mine is just set to `S:` which is a Azure Storage fileshare).

**Comment by pbering** [comment]
Closed due to inactivity...
