### ISSUE TITLE
Docker Image Build Is Failing 

### ISSUE THREAD

**Issue by itsravishankar** [Sitecore/docker-images#309]
I am using Windows 10 Pro to build sitecore docker images for the sitecore version 9.3.0

using the command ** .\Build.ps1 -SkipExistingImage -OSVersion "1909" **

and its failing while creating the sitecore assets
![image](https://user-images.githubusercontent.com/46617531/81643434-e81dd400-9468-11ea-80cf-67b14954e0c7.png)

Please help me to fix this issue.

Thanks in advance.

**Comment by pbering** [comment]
This is a Docker issue where the container does not have internet access. Please see https://github.com/docker/for-win/issues/2760#issuecomment-430889666 for the solution.
