### ISSUE TITLE
Sitecore Docker Build Issue

### ISSUE THREAD

**Issue by itsravishankar** [Sitecore/docker-images#310]
I am getting the below error when I ran 
     .\Build.ps1 -SkipExistingImage -OSVersion "1909" -Topology "xm","xp"  

OS Version - Windows 10 pro build 1909

![image](https://user-images.githubusercontent.com/46617531/81886346-cd21a000-95df-11ea-87d2-f8a339448342.png)

Please let me know, how to fix this issue.

Thanks

**Comment by pbering** [comment]
Hi, to help isolate the issue can you try to only run:

```PowerShell
.\Build.ps1 -OSVersion "1909" -Topology "xm"
```

**Comment by brueli** [comment]
Hi @itsravishankar .

In your logfile it reads "windowsservercore-1909". Make sure it's a supported image tag.

Here are my favorite links to see what's supported on certain operating systems / container hosts:
* [https://hub.docker.com/_/microsoft-windows-base-os-images](https://hub.docker.com/_/microsoft-windows-base-os-images)
* [https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2004%2Cwindows-10-2004](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2004%2Cwindows-10-2004)

Reading the documentation on those two pages helped me tremendously to understand what was wrong with my build configuration.

Hope this helps you too.

**Comment by pbering** [comment]
Closed due to inactivity. Please open new issue if needed.
