### ISSUE TITLE
build.ps1 issue

### ISSUE THREAD

**Issue by bobrdemantcom** [Sitecore/docker-images#319]
When I try to do an initial build of the Sitecore images by running

.\Build.ps1 -SitecoreUsername xxx -SitecorePassword xxx

 I get the following error

docker : no matching manifest for linux/amd64 in the manifest list entries
At C:\Users\bobr\source\docker\sitecore\docker-images-master\modules\SitecoreImageBuilder\1.0.0\Public\Invoke-Build.ps1:113
 char:17
\+                 docker image pull $tag
\+                 ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (no matching man...st list entries:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by pbering** [comment]
Seems you are running in Linux mode, switch to Windows by right clicking the whale in systray 🙂

/P

________________________________

**Comment by bobrdemantcom** [comment]
Doooooooh !!!!!! Thank you very much Per
