### ISSUE TITLE
Update readme file to explain the usage of SITECORE_LICENSE_LOCATION on 9.3 docker images

### ISSUE THREAD

**Issue by reyrahadian** [Sitecore/docker-images#326]
Was looking into 9.3 upgrade path from 9.2 docker images and found out that there's no documentation around how to mount the license file for 9.3 docker images which was supported in 9.2 docker images.

Per Bering pointed me to the following [article](https://sitecore.namics.com/2020/02/13/sitecore-docker-how-to-set-the-license-for-sitecore-9-3-containers/) that explains it in detail, however it'd be good to have the usage referenced in the readme file and an example on how to use it in one of the docker-compose test file.

If this is an accepted idea, I can work towards raising a PR for it.

**Comment by pbering** [comment]
Hi, that would be a awesome contribution! I imagine a _new_ section in the README.md and a link to that from the "Quick start" section.
