### ISSUE TITLE
Stuck at Sql server image builder

### ISSUE THREAD

**Issue by sanidhay** [Sitecore/docker-images#329]
# ISSUE

- [x] I have tried with the latest version of Docker for Windows (Stable or Edge) or Docker Enterprise.
- [x] Windows version is at least 1809 / ltsc2019.
- [x] Windows has the latest updates installed.

## Expected behavior

...

## Actual behavior
19:36:38:887: Processing 1 of 7 'mssql-developer:2017-windowsservercore-1909'...
Sending build context to Docker daemon  8.192kB

Step 1/8 : ARG BASE_IMAGE
Step 2/8 : FROM $BASE_IMAGE
1909: Pulling from windows/servercore
docker : no matching manifest for windows/amd64 10.0.17134 in the manifest list entries
At line:1 char:1
+ docker image build --isolation 'hyperv' --memory 4GB --build-arg BASE ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (no matching man...st list entries:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
...

## Additional information

- Output from `docker info`:

    ```text
    ...
    ```

- Are you running inside a virtualized Windows machine or physical:
- ...

## Steps to reproduce the behavior
.\Build.ps1 -SkipExistingImage -OSVersion "1909" -Topology "xm"

  1. ...
  2. ...

**Comment by pbering** [comment]
Hi, you need to switch to "Windows container", right click the whale in systray.
