### ISSUE TITLE
Need to build a "smart" way to download additional assets from dev.sitecore.net (non-WDP packages) 

### ISSUE THREAD

**Issue by jeanfrancoislarente** [Sitecore/docker-images#370]
Some assets on dev.sitecore.net are not ready for direct consumption by the repository. They need additional processing (convert to WDP or unzip).

As described in the [instructions](https://github.com/Sitecore/docker-images/blob/master/build/INSTRUCTIONS.md#experimental-publishing-service-not-automatically-build-because-of-missing-prerequisites-from-sitecore), some files are not ready for direct consumption by the build process and need to be manually downloaded and either converted and/or unzipped and placed into the InstallSourcePath of your liking.

We need to improve the logic in Download-Prerequisites.ps1 to:
- not download all files for all versions
- allow for downloading only the files necessary for the module(s) or features being built.

**Comment by vtml** [comment]
I quite like the way how Sitecore.HabitatHome.Utilities organises the assets.
