### ISSUE TITLE
Sitecore 10 SXA, JSS, CM variant missing node.js for Experience Editor

### ISSUE THREAD

**Issue by KKings** [Sitecore/docker-images#386]
# ISSUE

- [x] I have tried with the latest version of Docker for Windows (Stable or Edge) or Docker Enterprise.
- [x] Windows version is at least 1809 / ltsc2019.
- [x] Windows has the latest updates installed.

## Expected behavior

JSS powered sites should work in Experience Editor 

## Actual behavior

JSS powered sites throw an exception within Experience Editor.

"Ensure that Node.js is installed and can be found in one of the PATH directories. Current PATH environment variable is ..."

## Steps to reproduce the behavior

Setup and run a JSS site on the "community/sitecore-xp0-custom-sxa-jss-cm" image.

**Comment by vtml** [comment]
@KKings it will be great for you to review my PR if you have time.
