### ISSUE TITLE
Sitecore 10 JSS CM, CD missing Web.config changes

### ISSUE THREAD

**Issue by KKings** [Sitecore/docker-images#387]
# ISSUE

- [x] I have tried with the latest version of Docker for Windows (Stable or Edge) or Docker Enterprise.
- [x] Windows version is at least 1809 / ltsc2019.
- [x] Windows has the latest updates installed.

## Expected behavior

Sitecore JSS web.config transforms applied to CM and CD

## Actual behavior

Sitecore JSS web.config transforms applied to CM and CD

## Additional information

Similar issue was resolved for earlier versions, https://github.com/Sitecore/docker-images/issues/122

**Note:** sitecorejss_media.ashx Media Handler should be applied to the system.webServer/handlers

**Comment by vtml** [comment]
SXA CD is also missing web.config transform.
I am working on this now and will have a PR coming shortly.

**Comment by vtml** [comment]
@KKings it will be great for you to review my PR if you have time.
