### ISSUE TITLE
Cloning git repo wants to change line endings from unix to dos

### ISSUE THREAD

**Issue by GurliGebis** [Sitecore/docker-images#388]
# ISSUE
Cloning the git repo, no matter on Windows or Linux results in tags/sitecore-tags.md being changed from unix line endings to dos line endings.
There is no way to undo this, since git forces the change again immidiately back to dos line endings.

- [x] I have tried with the latest version of Docker for Windows (Stable or Edge) or Docker Enterprise.
- [x] Windows version is at least 1809 / ltsc2019.
- [x] Windows has the latest updates installed.

## Expected behavior
Checking out the repo should not result in files being changed.

## Actual behavior
Checking out the repo results in the tags/sitecore-tags.md file being changed by git from unix to dos line endings.

A suggested solution would be to change the logic that generates that file to make sure it is commited with dos line endings, to prevent git changing it when checking out the repo.

**Comment by jeanfrancoislarente** [comment]
Thanks @GurliGebis - I've reported this internally

**Comment by DavidMtbg** [comment]
Removing the following line from .gitattributes resolves this issue, but I'm not sure what the downstream effects are on the project (e.g. that must be in place for a reason):
https://github.com/Sitecore/docker-images/blob/master/.gitattributes#L6

**Comment by GurliGebis** [comment]
Thanks 😃

**Comment by GurliGebis** [comment]
Still broken - I did a clean clone of the repo, instantly the sitecore-tags.md file is marked as changed.

**Comment by GurliGebis** [comment]
```
me@mymachine MINGW64 /d/Inetpub
$ git clone https://github.com/Sitecore/docker-images.git CleanClone
Cloning into 'CleanClone'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 9872 (delta 15), reused 28 (delta 12), pack-reused 9826 eceiving objects: 100% (9872/9872), 1.14 MiB | 2.1R MiB/s
eceiving objects: 100% (9872/9872), 2.12 MiB | 3.69 MiB/s, done.
Resolving deltas: 100% (5538/5538), done.

me@mymachine MINGW64 /d/Inetpub
$ cd CleanClone/

me@mymachine MINGW64 /d/Inetpub/CleanClone (master)
$ git status
Refresh index: 100% (1268/1268), done.
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   tags/sitecore-tags.md

no changes added to commit (use "git add" and/or "git commit -a")

me@mymachine MINGW64 /d/Inetpub/CleanClone (master)
```

As you can see, a clean clone of the repo results in the file being marked as changed.

**Comment by jeanfrancoislarente** [comment]
Yes, we've re-reproduced it internally and it will be fixed. Unfortunately there are a couple of more pressing issues being worked on at the moment but this will definitely be addressed!

**Comment by jeanfrancoislarente** [comment]
Please give it a shot now @GurliGebis

**Comment by GurliGebis** [comment]
@jeanfrancoislarente it seems to be working now 👍
