### ISSUE TITLE
Script fails to convert to scwdp causing failure

### ISSUE THREAD

**Issue by geoffreysmith** [Sitecore/docker-images#404]
# ISSUE

- [x] I have tried with the latest version of Docker for Windows (Stable or Edge) or Docker Enterprise.
- [x] Windows version is at least 1809 / ltsc2019.
- [x] Windows has the latest updates installed.

## Expected behavior

Docker builds

## Actual behavior
```
22:45:51:689: Processing 8 of 33 'community/modules/custom-def-assets:10.0.0-1809'...
WARNING: 22:45:51:827: Optional source file '/Users/xxx/work/docker-images/build/packages/Data Exchange Framework 5.0.0 rev. 01466.scwdp.zip' is missing...
Sending build context to Docker daemon  7.215kB
Step 1/17 : ARG BASE_BUILD_IMAGE
Step 2/17 : ARG TOOL_IMAGE
Step 3/17 : ARG BASE_IMAGE
Step 4/17 : ARG ASSETS_IMAGE
Step 5/17 : FROM ${TOOL_IMAGE} as tools
 ---> 089849b3d870
Step 6/17 : FROM ${BASE_BUILD_IMAGE} as build
 ---> 71d3f266f3af
Step 7/17 : SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 ---> Using cache
 ---> 1bbef54c4b1d
Step 8/17 : ARG MODULE_NAME
 ---> Using cache
 ---> 6825b9c467e2
Step 9/17 : ARG ROLES
 ---> Using cache
 ---> cb00d396072a
Step 10/17 : COPY tools/ tools/
 ---> Using cache
 ---> bc99014c1707
Step 11/17 : COPY *.zip /wdp/
COPY failed: no source files were specified
Exception: /Users/xxx/work/docker-images/build/modules/SitecoreImageBuilder/1.0.0/Public/Invoke-Build.ps1:234
Line |
 234 |  … here-Object { $_ } | ForEach-Object { throw "Failed: $buildCommand" }
     |                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Failed: docker image build --build-arg BASE_IMAGE=mcr.microsoft.com/windows/nanoserver:1809 --build-arg TOOL_IMAGE=scr.sitecore.com/tools/sitecore-docker-tools-assets:10.0.0-1809 --build-arg
     | BASE_BUILD_IMAGE=mcr.microsoft.com/windows/servercore:ltsc2019 --build-arg ROLES=cm --file windows/10.0.0/modules/Dockerfile --tag 'community/modules/custom-def-assets:10.0.0-1809'
     | '/Users/xxx/work/docker-images/build/windows/10.0.0/modules/def-assets'
```

## Additional information

It appears that some files don't convert:

`ConvertTo-SCModuleWebDeployPackage -Path $filePath -Destination $Destination -Force `

- Output from `docker info`:

```
docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 49
 Server Version: 19.03.12
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Evaluation Version 1809 (OS Build 17763.1457)
 OSType: windows
 Architecture: x86_64
 CPUs: 2
 Total Memory: 2GiB
 Name: vagrant-2019
 ID: HKS2:DZAE:LVET:7CCI:NH5U:Z7G6:IDXW:JTRJ:PBBE:USRP:TGZK:DLVI
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false    
```

- Are you running inside a virtualized Windows machine or physical:
- Virtual

## Steps to reproduce the behavior

`pwsh ./Build.ps1 -SitecoreUsername xxxxx@xxxx.com -SitecorePassword xxxxxx -IsolationModeBehaviour EngineDefault -SitecoreVersion 10.0.0 -IncludeJss -IncludeSpe`

**Comment by vtml** [comment]
I have been downloading those files and converting them myself using Sitecore Azure Toolkit. You can then leave these files as specified in the `InstallSourcePath` parameter of the `build.ps1` script
https://sitecore.stackexchange.com/questions/10417/how-to-create-web-deploy-package-for-sitecore-modules

**Comment by geoffreysmith** [comment]
Thanks! I see why you're doing this on your own because the documentation for this is really not consistent with the rest or I'm doing something wrong. I created a Dockerfile **just to download and convert these packages**, it is up to 100 lines already:

https://gist.github.com/geoffreysmith/9d800f21cdfc474398ac7de2619f4caf

Things that are not listed as dependencies (I was running this on Linux, with a Windows Docker host -- there's no reason any of this really shouldn't be platform independent, it is just downloading and packaging files but I'm ignoring that):

1. Windows Server Core LTSC-2019
2. .NET Framework **SDK** 4.7.1
3. SQL 2016 CLR Types
4. Microsoft SQL Server Data-Tier Application Framework (17.0.1 DacFx)
5. SQL Server itself (!), I haven't got this far yet. Literally all errors related to creating Dacpacs on Google are Sitecore SIF or Sitecore Docker related. I think that either no one but Sitecore is using this functionality or Sitecore is using it wrong. Either way there has to be a better way around it.

I don't get why these build artifacts are included in the downloads from Sitecore, these scripts should just download the artifacts and not actually do anything with them.

**Comment by geoffreysmith** [comment]
Even going through those steps I cannot get a Docker SSDT environment working. Microsoft themselves has dropped support for DacFx on .NET Framework and focuses using it with .NET Core. The last MS-SQL update with Docker was 3 years ago. 

Sitecore Azure Toolkit which is built against .NET Framework 4.7.1. Since everything in the MSFT stack is .NET Core and the Sitecore Azure Toolkit doesn't do much, it seems the obvious choice to me would move the Sitecore Azure Toolkit to .NET Core.

Right now it seems my only choice would be to identify all the Sitecore assemblies needed to convert to WDP, [to dissemble to IL](https://hub.docker.com/r/bannsec/ilspy_docker) , recompile against .NET Core, create a Docker environment and convert the zip files to WDP. Seems like a lot of work,. if it works at all. Considering I have to login with Sitecore credentials to even get the assets, can't Sitecore just provide the build assets?

I'm in an on-prem environment where every dependency needs to be specified.

In any case, against the latest edition of Sitecore this build is failing.
