### ISSUE TITLE
`/tools/` directory contained scripts implementation are not aligned with new Sitecore Official Version 10.0.0 implementation 

### ISSUE THREAD

**Issue by peter-nazarov-namics-com** [Sitecore/docker-images#425]
`/tools/` directory contained scripts implementation are not aligned with new Sitecore Official Version 10.0.0 implementation (source Docker image: scr.sitecore.com/tools/sitecore-docker-tools-assets:10.0.0-1809) so that the implementation mismatches.

**Comment by bplasmeijer** [comment]
Hi @peter-nazarov-namics-com 

We are going to OSS the tooling image. 
Let me sync internal, and see what is the right approach here.

Bart

**Comment by peternazarov** [comment]
Thank you, @bplasmeijer

**Comment by jeanfrancoislarente** [comment]
The repo supporting the `scr.sitecore.com/tools/sitecore-docker-tools-assets` image(s) has been published https://github.com/Sitecore/docker-tools
