### ISSUE TITLE
Processing Engine not available for XConnect 9.1

### ISSUE THREAD

**Issue by joostmeijles** [Sitecore/docker-images#43]
The [Install-Databases.ps1](https://github.com/Sitecore/docker-images/blob/67ccf1c5a827bb090a9a20c875c3ca2c129f393a/images/9.1.1%20rev.%20002459/windowsservercore/sitecore-xp-sqldev/Install-Databases.ps1#L23) uses the filename as database name. In case of the processing engine db this does not match pre-defined variable in the SIF configuration file.

I fixed it here on lines 53 & 54:
https://github.com/avivasolutionsnl/sitecore-docker/pull/139/commits/cc45bbc16e5709117a2523fc386e0c947145fe6e#diff-e3209a96ec154a074174a7cbd8f86efa

NB. I would like to create a PR, but currently do not have a docker-images repo where I can test it.

**Comment by jeanfrancoislarente** [comment]
Since things have moved on to a no SIF approach, is this still valid @joostmeijles ?

**Comment by joostmeijles** [comment]
Still valid. 

The XConnect Processing Engine Docker image is currently missing.
A Docker Image that e.g. installs `Sitecore 9.2.0 rev. 002893 (OnPrem)_xp0xconnect.scwdp.zip\Content\Website\App_Data\jobs\continuous\ProcessingEngine` should be added.

**Comment by pbering** [comment]
Close this as it has been released!
