### ISSUE TITLE
Sitecore 10 XM1 Non Production SQL Init Job fails in AKS

### ISSUE THREAD

**Issue by rajcheval** [Sitecore/docker-images#470]
# ISSUE

- [ ] I have tried with the latest version of Docker for Windows (Stable or Edge) or Docker Enterprise.
- [X ] Windows version is at least 1809 / ltsc2019.
- [ ] Windows has the latest updates installed.

## Expected behavior
I am following Sitecore documentation to setup Sitecore XM1 on AKS
I created an AKS cluster with a Windows Node Pool.
I install help
Converted sitecore license file to base64.
Created CM, CD, ID certificates
I provisioned nginx ingress controller
defined secrets
defined external services without any errors(redis, solr, mssql)
I can access Solr UI
I created initialization jobs using this command
kubectl apply -f ./init/

Solr jobs runs fine.
MSSQL init job fails.
When looked at the failed job logs:
Start publishing dacpacs
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Named Pipes Provider: Could not open a connection to SQL Server [53]. .
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
sqlcmd exited with code 1
At C:\DeployDatabases.ps1:91 char:9
+         throw "sqlcmd exited with code $LASTEXITCODE"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (sqlcmd exited with code 1:Str
   ing) [], RuntimeException
    + FullyQualifiedErrorId : sqlcmd exited with code 1

...

## Actual behavior
MSQL init job should finish successfully
...

## Additional information

I started an interactive shell into Redis POD and verified that DNS resolution is working
I started an interactive shell into mssql POD and verified that MSSQL service was running.
The image that is the source for the failed mssql init job is scr.sitecore.com/sxp/sitecore-xm1-mssql-init:10.0.0-ltsc2019

- Output from `docker info`:

    ```text
    AKS Kubernetes Version 1.19.3
    ```

- Are you running inside a virtualized Windows machine or physical:
Run in Azure AKS

## Steps to reproduce the behavior

  1. Follow Sitecore 10 XM1 setup instructions and provision all services on AKS
  2.  kubectl apply -f ./init/    
  3.  kubectl get pods -o wide     It will show failed pods with name mssql-init-xxxxxx there will be 5 pods
  4. kubectl logs mssql-init-9gcvm     shows the error shown above

**Comment by rajcheval** [comment]
MSSQL users this image mssql-developer:2017-10.0.0-ltsc2019
I used kubectl exec to launch an interactive shell. 
I found that property NamedPipeEnabled is set to False.
However msql sql init container(image sitecore-xm1-mssql-init) is running script At C:\DeployDatabases.ps1:91 char:9 which seems to be connecting with mssql use namedpipes.

**Comment by GurliGebis** [comment]
I'm seeing this exact issue - not really sure how to proceed, since this seems to be the official way to spin up the databases in Azure SQL.

**Comment by GurliGebis** [comment]
@rajcheval I found the issue, together with Sitecore Support.
The problem is that the txt files in the secrets folder contains a linebreak, which is causing the problem. (Hopefully we will see a fixes container deployment package within a few months, so we don't have to do it manually)

Until then, just edit all the txt files in there, and make sure to remove the linebreaks, the deploy the secrets again using kubectl, followed by deployment of the init pods.

**Comment by rajcheval** [comment]
@GurliGebis  I was able to solve this issue a few weeks ago by editing the secret files to remove the 2nd blank line. I forgot to share the resolution here. Thanks for following up.
