### ISSUE TITLE
Development Watch directory location inconsistent between build community and Sitecore build scripts.

### ISSUE THREAD

**Issue by jammykam** [Sitecore/docker-images#478]
# ISSUE

- [x] I have tried with the latest version of Docker for Windows (Stable or Edge) or Docker Enterprise.
- [x] Windows version is at least 1809 / ltsc2019.
- [x] Windows has the latest updates installed.

## Expected behavior
The images built using the scripts would behave the same way as the images which are available in the [Sitecore Docker Container Registry](https://scr.sitecore.com/). In this case, I am specifically referring to the entry point scripts, they should both use the same watch directory to avoid confusion when building your own images vs consuming the pre-built images.
...

## Actual behavior
The [Development.ps1 watch scripts](https://github.com/Sitecore/docker-images/blob/master/build/windows/10.0.0/sitecore-assets/tools/entrypoints/iis/Development.ps1#L113) currentlly uses `C:\src` as the mount within the Docker container to watch for file changes. The Sitecore 10 images within SCR use `C:\deploy` as the watch directory.

![SCR Development.ps1](https://pbs.twimg.com/media/EoaB8ahW8AEkObu?format=png&name=large "SCR Development.ps1")
...

## Additional information

It is not entirely clear or obvious that the images in SCR are built from a different set of scripts and configs from those available in this repo. We obviously cannot change the internal Sitecore build scripts, but can only encourage the Sitecore Team to contribute back changes they make internally to the open source Community repo.

**Comment by jeanfrancoislarente** [comment]
Official contents of the scr.sitecore.com/tools/sitecore-docker-tools-assets image(s) has been published https://github.com/Sitecore/docker-tools

The next step now is to remove all 10.x + references to these items from this repository. #todo
