### ISSUE TITLE
Not issue - suggestion. Adding a ps script for copying website files to data/cm or data/cd

### ISSUE THREAD

**Issue by GoranHalvarsson** [Sitecore/docker-images#54]
Hey guys

I have a script where you can copy website files to your data folder. 
Don't forget to change volume in docker-compose for the sitecore images :
```
volumes:
      - .\data\cm:C:\inetpub\sc 

```
```

function CopySitecoreFiles($sitecoreContainerName, $outputDir){
    
    $dockerId = docker ps -q --filter name=${sitecoreContainerName}

    docker stop $dockerId

    $dockerIdAndPath = "${dockerId}:/inetpub/sc"

    docker cp $dockerIdAndPath "${outputDir}"

    docker start $dockerId
	
	Write-Output "Sitecore files from container, " $sitecoreContainerName  ", have been copied to " $outputDir
}


CopySitecoreFiles "windowsservercore_cm_1" "tests/9.2.0 rev. 002893/windowsservercore/data/cm"

CopySitecoreFiles "windowsservercore_cd_1" "tests/9.2.0 rev. 002893/windowsservercore/data/cd"

```

**Comment by pbering** [comment]
Hi there, what is the purpose / use case for this script?

**Comment by GoranHalvarsson** [comment]
The use case is for your local dev environment. to publish/deploy your dll's, configs, views etc.

**Comment by pbering** [comment]
In each Sitecore image there is a script embedded for this purpose: https://github.com/Sitecore/docker-images/blob/master/images/9.2.0%20rev.%20002893/windowsservercore/sitecore-xm1-cm/Sitecore/Scripts/Watch-Directory.ps1. It will continuously copy content from a volume mount into /inetpub/sc, see https://github.com/sitecoreops/sitecore-health-extensions/blob/master/docker-compose.yml#L27 and how to configure ENTRYPOINT: https://github.com/sitecoreops/sitecore-health-extensions/blob/master/docker-compose.yml#L22. In general you can use https://github.com/sitecoreops/sitecore-health-extensions as a reference for one way to wire up a solution.

**Comment by GoranHalvarsson** [comment]
Ah nice, I was not aware of this. Thank you 👍

**Comment by GoranHalvarsson** [comment]
I’ll close this one
