### ISSUE TITLE
Nuget Issue

### ISSUE THREAD

**Issue by D0cNet** [Sitecore/docker-images#60]
Hi,
I got an error, when trying to run the build (see screenshot)
"Invoke-WebRequest : The remote name could not be resolved: 'dist.nuget.org''.
Ran the command in PS console, and it worked. Maybe there is an issue with the context?
![SCDockerNugetIssue](https://user-images.githubusercontent.com/414979/63229677-1ec40800-c1d1-11e9-90e7-bd898fe1d982.PNG)

**Comment by pbering** [comment]
Hi, 

Sounds like there is no network connectivity inside your containers. Please check if you can do a basic ping like `docker run --rm mcr.microsoft.com/windows/servercore:1903 powershell ping 8.8.8.8`. If that is not working you can try to set a custom DNS on the docker engine (in the daemon config) like this:

```
  "dns": [
    "1.1.1.1"
  ]
```

**Comment by D0cNet** [comment]
Hi,
So that works
![image](https://user-images.githubusercontent.com/414979/63262170-465bb480-c253-11e9-83b7-a40cfe21dee3.png)

**Comment by pbering** [comment]
ok that it strange.... can you try to build again? Maybe it was just a temporary connectivity issue? You could also try to use `docker run --rm mcr.microsoft.com/windows/servercore:1903 powershell ping dist.nuget.org` to see if the hostname can be resolved.

**Comment by D0cNet** [comment]
Hi,
I've run the build about 10 times with the same result.
I ran the command with a timeout.
![image](https://user-images.githubusercontent.com/414979/63270155-9774a400-c265-11e9-8e31-22f3516098a2.png)

Maybe they are filtering pings.
Is there a way for me to add the nuget.exe as a package to the build, similar to the license.xml?

**Comment by pbering** [comment]
Here is the output from my machine (in Denmark):

```
docker run --rm mcr.microsoft.com/windows/servercore:1903 powershell ping dist.nuget.org                                                                                                                                                                                                                                                                                                                                                                                                                           Pinging cs2.wpc.gammacdn.net [152.199.23.209] with 32 bytes of data:
Reply from 152.199.23.209: bytes=32 time=9ms TTL=56
Reply from 152.199.23.209: bytes=32 time=10ms TTL=56
Reply from 152.199.23.209: bytes=32 time=10ms TTL=56
Reply from 152.199.23.209: bytes=32 time=10ms TTL=56

Ping statistics for 152.199.23.209:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 9ms, Maximum = 10ms, Average = 9ms
```

They accept ping/icmp, are you behind some corporate proxy or restrictive network policies?

**Comment by D0cNet** [comment]
I may be behind a managed firewall.But funny that issuing the actual command
`Invoke-WebRequest -Uri 'https://dist.nuget.org/win-x86-commandline/v5.0.2/nuget.exe' -UseBasicParsing -OutFile nuget.exe` works from my local powershell.
Could we make an alternative script path for nuget.exe from the local packages folder if this does not work?

**Comment by D0cNet** [comment]
Hi,
So i did the installation on another machine, which well definitely not be behind a firewall.
However, i am getting this error consistently
![image](https://user-images.githubusercontent.com/414979/63342522-b46aaf00-c319-11e9-8504-bb939eac23b4.png)
 _(was not sure if I should open another issue or not)_

**Comment by pbering** [comment]
Well that is good, it's another issue with corrupted zip files, see https://github.com/Sitecore/docker-images/issues/57

**Comment by D0cNet** [comment]
> Well that is good, it's another issue with corrupted zip files, see #57

Ok, this is still an issue. Why is it closed, was no automated solution found?

**Comment by pbering** [comment]
Closed for now since there is a workaround for handling corrupted downloads, ie. delete them (both in "InstallSource" and in each Docker context folder).

Please create a new issue if you can any suggestions on how we can automate verification of the zip.

I wish that Sitecore did supply checksums for each of their downloads, then we could verify them easily.

**Comment by D0cNet** [comment]
Ok, i agree on that.
Update:
It seems the corrupt zip might have been my issue also. I've successfully installed the docker images now.
I made a few changes to the sitecore-packages.json file, i'll submit pull request if you guys wanna have a look?

**Comment by pbering** [comment]
Please do submit a PR, always welcome :)

**Comment by jeanfrancoislarente** [comment]
Any update @D0cNet or can I got ahead and close this particular issue?

**Comment by D0cNet** [comment]
Nope all good. Finally "works on my machine" ;)

**Comment by jeanfrancoislarente** [comment]
Love it!
