### ISSUE TITLE
Sitecore Identity Server role Image

### ISSUE THREAD

**Issue by D0cNet** [Sitecore/docker-images#72]
Implement docker service for Sitecore Identity Server role

**Comment by jeanfrancoislarente** [comment]
Hey @D0cNet 

We're working on it ;)

We'll probably be rolling that out in conjunction with the next Sitecore product release.

**Comment by D0cNet** [comment]
I'm taking a stab at it if thats ok.
Will be updating soon

**Comment by jeanfrancoislarente** [comment]
Reach out to @bplasmeijer if you run into issues - I know he was experimenting with this as well

**Comment by D0cNet** [comment]
@bplasmeijer I have something working.
I had to make a few changes to the sitecore-xp-base and generate some certs for identity server etc .. is in line with what you have done/been doing?

**Comment by D0cNet** [comment]
@bplasmeijer @jeanfrancoislarente 
Got the role up, but i'm having certificate issues, Identityserver is not being found by the cm instance.

**Comment by pbering** [comment]
Images for Identity Server has been released so closing this one.

**Comment by anarsen** [comment]
> Images for Identity Server has been released so closing this one.

@pbering Out of curiousity, where are these images released?

I can't find 9.3-specific Identity Server images in this repository - only 9.2 ones. There's nothing on either dev.sitecore.net or Docker Hub either.

**Comment by pbering** [comment]
@anarsen it's only released for 9.2 XP and XC right now. I guess it will be created for 9.3 when we do XC for 9.3.
