### ISSUE TITLE
Long download time for Solr-7.5.0, no progress shown and no caching

### ISSUE THREAD

**Issue by daniel-simpson** [Sitecore/docker-images#88]
Building Sitecore 9.2.0 (all variants), and it is taking up to an hour to download solr version 7.5.0.

As this package is not seen as a prerequisite, it:
* downloads directly into the container
* needs to be re-downloaded if this step is stopped or higher steps are changed
* does not check if this package has been downloaded already before initialing the download

Not sure if this is just an issue on my internet connection or if there is a viable solr download mirror?  Ideally this would be one of the prerequisite packages downloaded and cached first (similar to SItecore packages) so this wait time isn't introduced needlessly and is only incurred once.

Thanks for all your great work on this repo!

**Comment by pbering** [comment]
Hi! I think it could be something with your internet connection. This is not what I'm seeing here:

```PowerShell
Invoke-WebRequest https://archive.apache.org/dist/lucene/solr/7.5.0/solr-7.5.0.zip -OutFile d:\temp\solr.zip -UseBasicParsing
```
Takes around 5 sec for the 161 MB.

Is it also slow when you do it from your host machine?

**Comment by daniel-simpson** [comment]
I guess it must just be my internet connection (Australia).

Direct from my host takes about 3 minutes
![image](https://user-images.githubusercontent.com/4665754/67244685-fcd35400-f4a5-11e9-8de7-fe60d2db9792.png)

Happy to close this, looks like a problem on my end.

**Comment by pbering** [comment]
Ok thanks for getting back. I will close this issue for now.
