### ISSUE TITLE
'Watch-Directory' breaks containers killing vital folders

### ISSUE THREAD

**Issue by sshushliapin** [Sitecore/docker-images#89]
I've got `Watch-Directory` configured to track changes in my published website folder (similar to this [example](https://github.com/sitecoreops/sugcon2018-docker/blob/master/docker-compose.yml#L23)). There might be folders that already exist in Sitecore (e.g. `App_Config` or `App_Data`). Removing these folders locally before publishing kills similar folders _inside_ the container including all the other default Sitecore files. As a result Sitecore instance dies and container have to be recreated.

Should the script remove files only preserving the directories?

**Comment by jeanfrancoislarente** [comment]
Which script is removing the files @sshushliapin?

**Comment by pbering** [comment]
I think I know your problem. The case is if you for example create a folder called `sitecore` in the root of the web project that is mounted into the container where the sync script watches for changes. If you then delete the folder `sitecore` then the filewatcher that is watching deletes: https://github.com/Sitecore/docker-images/blob/master/windows/9.2.0/sitecore-assets/tools/scripts/Watch-Directory.ps1#L101 will delete that folder **including** all the files already in the base image.

This behavior is what you want for your "own" folders but not standard folders such as `sitecore`, `App_Data`, `App_Config`, `Views` (?) and `sitecore modules`.

Any good ideas on how we should approach this?

As I see it we have to following options:

1. Never delete folders, **only** files.
2. In "standard" folders only delete files else delete both files and folders.
3. Keep behavior as is.

I'm leaning into 1 which is simple to change or 3 which is even simpler... :wink:

**Comment by sshushliapin** [comment]
+1 for option "1" from me. There should be no harm if some folders are left inside a _dev_ container.

**Comment by jeanfrancoislarente** [comment]
Ah yes  I get it now, agree that option 1 is probably a good approach. Wouldn't harm to leave other folders there as long as the files are cleaned up.

**Comment by ambrauer** [comment]
Looks like this fix didn't quite make it to the 9.3.0 version:
https://github.com/Sitecore/docker-images/blob/6c20fb2f7eb47d7cae6bd6f55a85c89732e53894/windows/9.3.0/sitecore-assets/tools/scripts/Watch-Directory.ps1#L103

I'm happy to create a new issue if you don't want to re-open this one.
