### ISSUE TITLE
Mount license.xml file as local volume

### ISSUE THREAD

**Issue by stephenpope** [Sitecore/docker-images#9]
Would it be better to have users mount their `license.xml` file into the data directory using the `-v` or `--volume` flag when starting the docker image.

This would : 

1. Reduce the risk of people accidentally pushing an image into the public domain with their license file baked in
2. Allow people to update their license file without rebuilding the whole docker image

**Comment by pbering** [comment]
Hi Stephen! Thank you for your suggestion. I can follow point 1 and agree that this *might* be the way to go, even tough it will require a bit more work to use the images (finding license, placing it the correct place, mount it) compared to embedding the license like now.

For point 2 I will argue that you should always build all images anyways, for example weekly, so you Sitecore images contains updated OS patches from microsoft/windowsservercore. So in my opinion its not a problem.

I'm thinking that if we do it, making SIF use a dummy license and the configure the images to require a mounted license, then users of this repo could just inject their own license if needed by using a modified version of Build.ps1.

Anyone else has any thoughts/comments on this issue?

**Comment by jeanfrancoislarente** [comment]
Just from a sensitive data and maintainability side of things, I like the idea of mounting the license as a volume. Although the idea is to build weekly / often, some may choose to use these images for a few months. 
As for complexity for using the images, the hope is to have samples in the docker-demo repo which will have example compose.yml files which pretty much show users how to mount. 

It doesn't have to be a high priority enhancement, XP + XC image building is probably higher on the priority list but certainly could be a nice "quick win" for someone to contribute.

**Comment by stephenpope** [comment]
Yup .. i was thinking a dummy license file would be the way to go, SIF would process it and then the user would just mount `/data/license.xml` (or wherever it ends up) to their local version (at the end of the process rather than have it involved in the SIF process where it moves it around etc).

**Comment by pbering** [comment]
We need to remember to delete the dummy license after SIF install, can't mount an existing file on Windows (nor an existing non empty directory).

**Comment by Ben-m-s** [comment]
May you please doble check whether this enhancement has already been satisfied with previous PRs?

The Data folder is being linked as volume to build the images, therefore, the license file which is stored in the Data directory is never copied to the image/container.

The demo repository has docker-compose files to show how to specify the location of the Data folder, among other volumes.

**Comment by joostmeijles** [comment]
@stephenpope would mounting the `license.xml` file open up the way for having a public Sitecore container registry (with authentication)?

**Comment by joostmeijles** [comment]
We added runtime mounted license support to XP and XC images, e.g. https://github.com/avivasolutionsnl/sitecore-docker/blob/master/xp/sitecore/Boot.ps1

Approach is basically;
- use dummy license during build
- bind mount directory with real license during runtime

**Comment by stephenpope** [comment]
Closing (as implemented!)
