### ISSUE TITLE
Connecting to SQLDevin SSMS requires 'Trust server certificate' option

### ISSUE THREAD

**Issue by RAhnemann** [Sitecore/docker-images#99]
When you provision a new SQLDev 
`docker run --publish 44010:1433 --mount type=bind,source=d:/docker/sitecore_data/demo/sql,target=c:/data --name sql_xm_920  sitecore-xm-sqldev:9.2.0-windowsservercore-1903`
You can't connect out of the box to SQL in SSMS.  You have to navigate to the Connection Properties, check the "Trust server certificate" to allow the connection. Otherwise you get an error about "The certificate chain was issued by an authority that is not trusted"

**Comment by pbering** [comment]
The SQL Server installation on Windows is the same as the official Windows docker images (ours is just running on more recent Windows versions) which does not have "Forced Encryption" enabled by default so I think this behavior is expected (same experience when connection to Azure SQL). 

I'm no SQL server expert so if there is anyone that knows something is wrong here or should be configured differently please say so :)

Else I will suggest that we close this issue for now.

**Comment by jeanfrancoislarente** [comment]
I agree @pbering this is expected behaviour and something people will just come to know from running SQL images in a development environment.
